### ISSUE TITLE
What are your thoughts in including an option for audio playback rates?

### ISSUE THREAD

**Issue by queuebit** [igrigorik/videospeed#122]
I often listen to podcasts in Chrome using Overcast web player (<https://overcast.fm/+BmGXbt60Q/> for example), and it would be nice if I didn't have to set the playback rate every time I open a new episode, similarly to how `videospeed` works for videos.

`$('audio')[0].playbackRate = 2.5` seems to work to set the playback rate in the Chrome console. (even though the Overcast UI isn't shown)

Is this something you think fits with the extension?

**Comment by igrigorik** [comment]
Hmm. Conceptually, and if I squint really hard.. yes. :)

However, it's not clear to me how we'd implement this in practice because unlike a video, it's not at all clear where we'd place the controller. Perhaps we could avoid showing the controller period.. but that has its own set of failure scenarios. In other words, there is a lot of implementation risk here. =/

**Comment by queuebit** [comment]
I'd say just put the controller on the top left corner of the host page.

But the simplicity and focus of the extension is great, so I'm fine either way.

Thanks!

**Comment by igrigorik** [comment]
Closing this for now as wontfix for now. We can revisit if there is more demand in the future.

**Comment by rdp** [comment]
+1 here, just wished for this today...
even if it's located upper left :)

**Comment by okyr-ux** [comment]
👍

**Comment by pepijnmm** [comment]
@okyr-ux audio speed is now already an option as you can see at the end of "Feature Request - Add option for HTML5 audio element" above your message
