### ISSUE TITLE
Question: Add speed controler for <audio>?

### ISSUE THREAD

**Issue by cliffordfajardo** [igrigorik/videospeed#158]
Today I listening to a podcast online and wanted to increase the playback speed. It was fairly easy to do that after grabbing the `audio` element and setting it's playback rate.

```
var audio = document.getElementById("myAudio");
audio.playbackRate = 0.5;
```

My question is: would it make sense to open a PR & write the code for this? Or is this project focused on only on videos?

**Comment by igrigorik** [comment]
Related discussion: https://github.com/igrigorik/videospeed/issues/122

It would be a relatively simple thing to add. The simple solution for the controller would be simply to hide it for audio - i.e. keyboard shortcuts only. The more involved solution would be to to show the speed on the icon in the toolbar..

**Comment by alystair** [comment]
Oops didn't see this... +1!

**Comment by canarslan12** [comment]
as far as I see, Soundcloud is not using `<audio>` so it's not related with this issue

**Comment by george-viaud** [comment]
I believe this should be a fairly simple thing to add (perhaps just updating the selector pattern) as HTML5 Audio and Video both support the same playbackRate variable if I'm not mistaken.

This is super useful when listening to podcasts online! Right now I have a custom HTML file I use to playback podcasts locally at high speed which is cumbersome - it would be great if this feature was exposed in all online HTML5 Audio I listen to.

Many thanks!

**Comment by queuebit** [comment]
If I stream an `mp3` in Chrome directly from source, it wraps it in a video tag and `videospeed` ends up showing like this.

Just sharing what happens in one specific case:

<img width="366" alt="screen shot 2017-07-31 at 11 47 22 am" src="https://user-images.githubusercontent.com/945262/28786105-35c968ee-75e6-11e7-8cc4-0e50814a6cfc.png">

**Comment by canarslan12** [comment]
Yes it's easy in terms of changing speed but overlay may(almost every time) not shown. There need to be something to show it and make hot keys available. And there's another question, where hotkeys available, on anywhere on site or only focused on "audio" tag. Most of the sites there is no displayable audio element, they are hidden.

George Viaud <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (31 Tem 2017 18:43):


I believe this should be a fairly simple thing to add (perhaps just updating the selector pattern) as HTML5 Audio and Video both support the same playbackRate variable if I'm not mistaken.

This is super useful when listening to podcasts online! Right now I have a custom HTML file I use to playback podcasts locally at high speed which is cumbersome - it would be great if this feature was exposed in all online HTML5 Audio I listen to.

Many thanks!

**Comment by igrigorik** [comment]
One option to explore here is to use the plugin icon as an indicator for current speed -- it gets quirky when you have multiple videos on the page, but it could be an interesting option.

**Comment by canarslan12** [comment]
I love that idea but I do not know how to put badge to icons, maybe one day I will implement it and push. who knows?

**Comment by queuebit** [comment]
I just took a quick look at [chrome.browserAction.setBadgetText](https://developer.chrome.com/extensions/browserAction#method-setBadgeText) but `chrome.browserAction` kept showing up as `undefined`. #ChromeExtensionNewbie

`¯\_(ツ)_/¯`

**Comment by studgeek** [comment]
This would be great for http://www.npr.org/. It seems to use <audio> as well.

I think an initial cut that just adds a floating iframe with the controls would be great. That seems much simpler than figuring out how to add icons to the toolbar. Even simpler, but not as useful, would be just adding menu items to the video speed extension menu.

**Comment by canarslan12** [comment]
For adding badge we need background task which manages this. First, I need to ask @igrigorik, am I allowed to do that, will he pull that change? 
manifest.json:
```
   "background": {
      "scripts": [ "badge-manager.js" ]
   }
```

**Comment by igrigorik** [comment]
@canarslan12 yes. To confirm, we're talking about adding current speed as an overlay to the icon in the toolbar, correct? We might have to fiddle with how we present it, but that's a second step.

**Comment by jacobcolbert** [comment]
FWIW I've been using a version where I just changed the selector to pick up all audio and video tags with no other changes and it works exactly as I would like. If the site has a nice little area for the audio tag to live in the overlay shows up as expected in the top left of that area, and otherwise is in the top left of the screen. This seems as consistent with video behavior as possible. I think I would prefer this to having it in the badge.

**Comment by nucatus** [comment]
Since both, audio and video playback, are global to the page, although it can be argued that is global to the whole browser instance, why not place the speed badge in the address bar, on the right side?

For instance, the google translate plugin is using that area for displaying the translate toggle menu. However, the only use case I thing the video badge makes more sense is in the full screen mode, when the user has no other way of knowing the playback speed. 

In this way, the audio and video can have a consistent behavior.

Moreover, from my perspective, it might make sense to completely drop the buttons and rely only on the key bindings. I guess this is the most frequent usage pattern among the audience of the application.
