### ISSUE TITLE
Controls vanishing

### ISSUE THREAD

**Issue by kjakich** [igrigorik/videospeed#165]
More of a request than a bug:  as an end user, I would like the 'on-player' controls to remain expanded when hovering over them, so that I can click fastforward multiple times without the controls 'hiding'. Thanks! 
![controls](https://cloud.githubusercontent.com/assets/4339327/21914720/de065de4-d999-11e6-8511-481e74b5eb29.png)

**Comment by igrigorik** [comment]
Thanks for reporting this! We actually already (recently) fixed this - see https://github.com/igrigorik/videospeed/issues/160.. The fix will go out in the next release. In the meantime, you can try installing the latest version as an unpacked extension.

**Comment by SimonIMG** [comment]
Hi. I love this extension but I'm still finding that this is an issue.

When I hover over the controls and I click the skip ahead button, it all works fine, but unless I click it again in quick succession, it collapses (and I end up pausing the video on YouTube).

It's not a great UX because it might take me a couple of seconds to realise I need to skip forward (or back) again, and by that time, the buttons have collapsed.

Could we update this so the buttons stay expanded until the mouse pointer is no longer hovering on the buttons?

I have version 0.5.2 installed.
