### ISSUE TITLE
Control panel position issue

### ISSUE THREAD

**Issue by newro** [igrigorik/videospeed#178]
YouTube displays the video title on the top left of the playback screen.
The control panel appears at the same position, so that the playback speed information and the like are obscured.
It is not easy to change the panel position due to the video title of the mouse drag event.
You need to be able to specify the panel position as an option, or to remember the panel position like the playback speed.

**Comment by igrigorik** [comment]
Do you have a demo page?

**Comment by newro** [comment]
The description was a little short.
The YouTube page does not work the way I described it.
The page I was describing was a page that included a YouTube video.
You can see here.
https://developers.google.com/youtube/youtube_player_demo?hl=en

**Comment by igrigorik** [comment]
Ah, embeds.. Looks like they updated their CSS. Thanks for reporting it!

**Comment by SuzanneShelton** [comment]
I am unable to move the controller on Netflix because it is covered by a large arrow to return to navigation. I can see the hand and even change the speed, but not move the controller. I am using it to watch a Spanish language show to improve my Spanish, so the ability to slow down playback would be a huge help. Here's the link to what I'm watching:
https://www.netflix.com/watch/70308005?trackId=14170287&tctx=0%2C0%2C54fbf992-a191-471f-af13-a85c1879e4ee-231651499
Here's a screenprint of the problem:
 ![image](https://cloud.githubusercontent.com/assets/25985733/23269292/bea30bc8-f9b5-11e6-9306-cd03802efb1b.png)

I am able to move the controller on other sites. 

Thank you for your work on this most helpful utility.

**Comment by igrigorik** [comment]
Thanks for reporting this guys! Both YT embeds and Netflix should be fixed in master..

**Comment by newro** [comment]
Thank you. I look forward to it. When will I be able to use the version that reflects the source?

**Comment by igrigorik** [comment]
Will go out with next release.. I'd love to triage some other outstanding bugs first though. Soon.. :)
