### ISSUE TITLE
Doesn't work on CNN

### ISSUE THREAD

**Issue by coloradude** [igrigorik/videospeed#182]
Just try it for yourself. Removes the video but the audio still plays and it looks like there are two layers of video.

**Comment by igrigorik** [comment]
Oi.. that's an interesting one. Thanks for reporting it.

**Comment by igrigorik** [comment]
I can't reproduce this on http://www.cnn.com/videos: video loads and I can use shortcut keys to adjust playback. It does appear that there are two controllers popping up, but that's due to an implementation bug on CNN side.. not much we can do about that :(

Please try disabling any adblockers and/or running extension in a clean profile. My hunch is that this is due to some odd interaction with another extension. If the problem persists, please feel free to reopen.

**Comment by coloradude** [comment]
Turns out it was a css issue. My bad.

**Comment by igrigorik** [comment]
Great, glad to hear it's working!
