### ISSUE TITLE
speed controller increase or decrease all the way rapidly 

### ISSUE THREAD

**Issue by moon17n** [igrigorik/videospeed#192]
when I use the shortcut for speed controllers, specially coming from another browser (or another tab), or sometime even after some time,,,, I see instead of increasing or decreasing the speed by the increment that I aim (by pressing the shortcuts), it actually go crazy and either increase the speed rapidly all the way, or decrease the speed rapidly all the way to the end. so this cause so much frustration and problem. I have to go decrease or increase until in comes back to the desired speed... 

I tried deactivating and reactivating and also reinstalling the plugin, but still it has problem. I am using Chrome browser.

**Comment by igrigorik** [comment]
Hmm, odd. The two reasons I can think of are: you're hitting the speed buttons before the video has loaded and page is interactive -- i.e. keypress events are queued up behind other work and then fire all at once? Alternatively, maybe you're hitting the shortcut keys by accident? 

- Please try reconfiguring your shortcuts
- Try disabling "remember speed" option and see if that helps
- If none of the above work out, try installing extension in a clean profile (or run it in incognito mode, with all other extensions disable) and see if the problem persists -- it could be due to some funky interaction with another extension.

If none of the above work out, please reopen and we can try to debug further.
