### ISSUE TITLE
Automatically drop to 1.0x when catching up in live stream

### ISSUE THREAD

**Issue by chrisdolan** [igrigorik/videospeed#207]
I often watch liveplayer tech talks by pausing for a while and then playing back at ~1.4x. But if I accidentally catch up to the present, it repeatedly pauses to buffer then plays at fast speed. I'm curious if videospeed can detect that it's caught up to Live and can automatically drop down to 1.0x? It's unclear to me if HTML5 can provide that signal in general or if that would have to be a YouTube/Google-specific feature.

**Comment by igrigorik** [comment]
What would happen when the next chunk arrives? In theory, a good player implementation should adjust the bitstream quality "on the fly" as it observes bandwidth fluctuating: you start with a 1080p stream, run into a rebuffer that pauses the video, the extension downgrades video to 1x and player switches down to 720p. Now you're at 720p with 1x speed that you didn't request -- would be jump back to 1.4x? 

We *could* detect when a rebuffer happens, but I'm not convinced that this is a good signal to jump down to 1x as an automatic response. If you're continuously bumping into this case you'll feel equally frustrated because this logic will keep resetting your speed.

**Comment by xftroxgpx** [comment]
I've a way to detect when livestream reaches end without false positives(i believe):
check this permalink to the code: https://github.com/xftroxgpx/videospeed/blob/5a02d5700815c833c65aa8ef6fb67e1105be5347/inject.js#L92-L119

If anyone thinks there's a false positive, maybe let me know. My tests show none, thus far. So, I'm using it =)

**Comment by xftroxgpx** [comment]
Actually I just found a false positive whoops =) it's when seeking in the livestream, it happens sometimes, and sometimes it doesn't, even though in all cases the seeked to time wasn't prebuffered!

**Comment by SeanSilke** [comment]
Encountered same behaviour with facebook video. Speed drops to 1.0x when video player reach the end of download buffet. The new downloaded chunk start playing with 1.0x.
@chrisdolan does this issue and yours have the same origin?
@xftroxgpx Do you suggest to try yours version of plugin?

**Comment by xftroxgpx** [comment]
>@xftroxgpx Do you suggest to try yours version of plugin?

@SeanSilke my fork is a mess, I wouldn't recommend it unless you're me:)

**Comment by igrigorik** [comment]
As I mentioned earlier in https://github.com/igrigorik/videospeed/issues/207#issuecomment-297257262, this space has no obvious solution and it's really hard to disambiguate a buffer stall from "end of stream for live video". Similarly, it's not obvious that you'd want either of those cases to trigger 1x speed automatically.. we'd end up with another configuration flag and a complex-and-imperfect code path to maintain. 

As such, I'm going to close this.. I don't think we want to take on this burden. If you guys disagree, feel free to reopen.
