### ISSUE TITLE
Volume controls & playback value changed observer & "Media Playback Controller" would be a much more descriptive name

### ISSUE THREAD

**Issue by wesamco** [igrigorik/videospeed#243]
just realized the internet plummer Googler guy I follow on twitter was behind this useful extension that had literally _saved at least couple months of my life_ since I started using it 1.5 years ago 💗😄

[HTMLMediaElement](https://developer.mozilla.org/en/docs/Web/API/HTMLMediaElement) has the volume property too, most websites don't implement keyboard volume controls for custom/styled players, and it's annoying (it should be default browser behavior for focused media elements (IMHO)).

lets implement
- volume controls
- a value changed but not by user observer, some custom players like Facebook's revert speed to 1.0 even though it has buffered..

"Media Playback Controller" would be a much more descriptive name because it already does more than changing videos speed, it works on default audio player too (open audio file in a tab), it's a playback controller with keyboard shortcuts.

**Comment by igrigorik** [comment]
@wesamco glad it's been useful! :-)

FWIW, I'm inclined to keep this plugin focused on speed adjustments. If nothing else, for my own sanity because even with just that scope it's already sufficiently hard to make it work well across the web (look at the bug count!). Also, nothing prevents another plugin from tackling the audio controls and other bits, and smaller + more contained plugins are a win in my books.

One alternative future I _could_ see here is if I ever get around to refactoring some of the key-handling logic. Specifically, the thought is to abstract the key-handling code into an extensible mechanism that could be configured by advanced users right from their options console -- e.g. plugin passes the video instance, you define your JS logic that you want to run on it; this way you can implement custom logic like volume controls, without baking this stuff into core.
