### ISSUE TITLE
videos freezing and going back to start point

### ISSUE THREAD

**Issue by davister** [igrigorik/videospeed#253]
https://www.pilatesanytime.com/class-view/435/video/Pilates-Mat-Workout-by-Rael-Isacowitz

Not sure if you'll be able to see as this is a paid service (although they offer a free trial).  Even changing quality to 404p the same issue happens. Video freezes every 30 seconds or so and reverts to a black screen. The video quickly shows 0.00m (video start point) with a black screen for a second and then the video reverts to the point it froze and stays there frozen.  To restart I need to hit pause and play again.

I have good quality fibre optic internet (around 15ms Ping and 70MB download speed). As soon as I change the speed to 1.00 the video works fine.

**Comment by igrigorik** [comment]
Looks like all videos on that site are behind the paywall, can't test on this end.

That said, I don't think there is anything we can "fix" on this end with regards to this behavior. With 99% certainty, the issue is that the player doesn't have the right adaptive streaming logic in pace -- you're exhausting your buffer, the video pauses due to rebuffer, and after pause+play it fetches the next chunk. This is an issue on their end -- might be worth sending them a ping and a heads up.

**Comment by davister** [comment]
Many thanks for the reply. I’ve passed this to the 3rd party site. Really appreciate your time looking into this.
Kind regards,
David.

On 27 Aug 2017, at 20:03, Ilya Grigorik <notifications@github.com> wrote:

Looks like all videos on that site are behind the paywall, can't test on this end.

That said, I don't think there is anything we can "fix" on this end with regards to this behavior. With 99% certainty, the issue is that the player doesn't have the right adaptive streaming logic in pace -- you're exhausting your buffer, the video pauses due to rebuffer, and after pause+play it fetches the next chunk. This is an issue on their end -- might be worth sending them a ping and a heads up.
