### ISSUE TITLE
Port to Firefox (WebExtensions)?

### ISSUE THREAD

**Issue by yoasif** [igrigorik/videospeed#271]
Hi, following up from a post on reddit commenting about this extension. https://www.reddit.com/r/firefox/comments/73htw6/video_speed_control_does_not_work_well_at_faster/

The user was likely using another extension on Firefox that caused issues. 

Firefox now uses WebExtensions, which are similar to Chrome extension APIs.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions

It'd be nice if this addon supported Firefox! :)

**Comment by igrigorik** [comment]
@codebicycle how much of a difference is there between the codebases? Could we refactor and merge them into one -- headache?

**Comment by sainaen** [comment]
@igrigorik 
AFAIK, Firefox doesn't support ShadowDOM/WebComponents by default yet and I think that's the biggest difference. Actual extension API-s are very similar in recent versions.

**Comment by igrigorik** [comment]
@sainaen gotcha. Hopefully that'll be solved soon.. at which point we can revisit, if it makes sense. Mostly want to make sure that folks have latest bug fixes and improvements.

p.s. thanks for maintaining the FF version!

**Comment by codebicycle** [comment]
Some changes are safe to make, like replacing `chrome.extension` with `chrome.runtime` while others might take more consideration.

To use `storage.sync` in Firefox, the add-on ID must be explicitly set in the manifest file. Google Chrome does not recognize the applications key and will show a warning if you include it. I used `storage.local` instead of `storage.sync` for this reason but the better option is to just have different manifest files for Chrome and Firefox.
 
There are differences in how Chrome and Firefox handle event propagation.
I had to change addEventListener(..., true) to false.

ShadowRoot is not implemented in Firefox, so I had to work around that.


@igrigorik thank you for this wonderful extension! Time is precious!

**Comment by igrigorik** [comment]
> Some changes are safe to make, like replacing chrome.extension with chrome.runtime while others might take more consideration

+1

> To use storage.sync in Firefox, the add-on ID must be explicitly set in the manifest file. Google Chrome does not recognize the applications key and will show a warning if you include it. I used storage.local instead of storage.sync for this reason but the better option is to just have different manifest files for Chrome and Firefox.

Hmm, so local doesn't give you sync between profiles.. I guess we could feature detect it and default to `sync` if available? Ideally, we'd have same manifest file -- a warning is OK, as long as it doesn't prevent your average user from using or installing the extension.

> There are differences in how Chrome and Firefox handle event propagation.
> I had to change addEventListener(..., true) to false.

Huh, interesting. Do you have more details / repro case? Sounds like a web-compat bug that we should file.

> ShadowRoot is not implemented in Firefox, so I had to work around that.

Available behind a flag: https://bugzilla.mozilla.org/show_bug.cgi?id=1205323 - let's hope it'll get flipped soon.
