### ISSUE TITLE
[Bug] Extension stops working after video stops and loads new

### ISSUE THREAD

**Issue by md100play** [igrigorik/videospeed#284]
I use the chrome extension on Plex and it had been working great until recently. Now, after an episode completes and plex starts to play the next video, the speed reverts to 1x and the extension disappears and does not respond to keyboard controls. I have to refresh the plex page and then play the video to bring back speed control.

**Comment by md100play** [comment]
Pausing and playing videos does not cause this issue, only plex going to the next item in a playlist causes this problem.

**Comment by captainevdo** [comment]
After encountering this same issue in plex, I checked to see if it affected other playlists (youtube etc), but this appears to be isolated to plex.  Issue has been ongoing for a few weeks so dont know if it is the extension or the latest plex rollout that nuked it.

**Comment by miniquandt** [comment]
Yeah, I posted a comment similar to this (but not as in depth). I was told to uninstall and reinstall by "try installing the unpacked extension from git, and confirm if that fixes your problem?" 

I tried reinstalling it, but as far as I'm aware I have not found out how to install from Git. I just reinstalled from the chrome webstore. It did not affect anything.

Here is my bug report. It got closed because it took me 2 weeks to remember to come back so they closed it (for good reason).
https://github.com/igrigorik/videospeed/issues/276

**Comment by captainevdo** [comment]
Miniquandt, you solved it.  Installing the extension from here has completely fixed the plex problem.  On the mainpage in the upper right, click "clone or download" and download as a zip file.  Extract the zip to a folder and remember the location.  In the chrome extensions menu, enable developer mode and click "enable unpacked extension".  navigate and select the prior folder and viola it works.

**Comment by miniquandt** [comment]
OOOOOOHHHH Thats how it works!!!!! I will give it a try. Thx I was trying to figure out what the Dev meant.

**Comment by md100play** [comment]
Installing from GitHub did fix the issue. So I guess the chrome store needs to get an updated version from the github source? I don't think it should matter where the code comes from as long as it is the same code.

**Comment by md100play** [comment]
I'm going to close out this issue, but I do recommend that the maintainers update the chrome store version so that other users don't run into this problem.

**Comment by igrigorik** [comment]
0.5.0 should be rolling out now with the fix. 👍
