### ISSUE TITLE
Video Speed regression bug.

### ISSUE THREAD

**Issue by OneMaskedNinja** [igrigorik/videospeed#296]
When i lower a videos speed to less than or equal to x0.06 any attempts to adjust the speed are ignored and the playback speed is stuck at x0.02, resulting in the need for a reload.

**Comment by canarslan12** [comment]
What is your browser and browser version? 
How do you lower speed below 0.06? I can't reproduce this

**Comment by OneMaskedNinja** [comment]
I am using the latest version of Google Chrome.

**Comment by igrigorik** [comment]
@canarslan12 have you had a chance to investigate this one?

**Comment by canarslan12** [comment]
As far as I know 0.00 speed has no problem now,
I think we should not limit about it, allow 0.00 and add another key for `frame by frame speed`(0.07)

**Comment by igrigorik** [comment]
@canarslan12 I'm hesitant of allowing 0.0 because it's completely non-obvious to the end user when the speed is set 0 vs video is paused. I think we already saw some folks trip up over this — see https://github.com/igrigorik/videospeed/issues/277.

Closing, the issue flagged here should be resolved now.
