### ISSUE TITLE
Keeping the Speed when video is paused

### ISSUE THREAD

**Issue by dcericola14** [igrigorik/videospeed#312]
I use this to speed up my online lectures and it is absolutely amazing, but If I pause the video to take notes or something the video speed by default goes back to 1.0. Is there a way to keep the video sped up so when I hit play it continues playing at the same speed vs. playing at normal speed?

**Comment by igrigorik** [comment]
That's how it should work by default. My guess is that the video player on your course site is overriding the speed setting every time you hit play.. and, unfortunately there is nothing we can do about that on this end. Do you have a public URL we can test against?

**Comment by dcericola14** [comment]
I am not confident this will work, but this is the URL I can provide.

https://mediasite.umaryland.edu/mediasite/catalog/catalogs/pharmacy


On Feb 19, 2018 8:11 PM, "Ilya Grigorik" <notifications@github.com> wrote:

That's how it should work by default. My guess is that the video player on
your course site is overriding the speed setting every time you hit play..
and, unfortunately there is nothing we can do about that on this end. Do
you have a public URL we can test against?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/igrigorik/videospeed/issues/312#issuecomment-366839404>,
or mute the thread

**Comment by igrigorik** [comment]
It does! The issue here is that the video player on that site has its own built-in speed controls and whenever "play" is executed it resets the playbackRate to its internal value.

![image](https://user-images.githubusercontent.com/10652/36634928-32499b84-1961-11e8-939c-87bd259d38a1.png)

The "fix" here would be to file a bug against the player: either it shouldn't reset the speed, or it should listen to externally triggered 'ratechange' events and sync its local state to that. That's what we do in the plugin: https://github.com/igrigorik/videospeed/blob/master/inject.js#L71-L82

Closing because there we can't "fix" this on this end.
