### ISSUE TITLE
New shortcut to 'restore' original speed (1x)

### ISSUE THREAD

**Issue by ElijahLynn** [igrigorik/videospeed#33]
I use this extension quite a bit to watch slow motion replays of baseball. After I have replayed the desired section in slow mode I always want to restore the speed, which requires me to press multiple times to get back to 1x. Would a PR be accepted to add a keyboard shortcut for the "r" key to restore to a hardcoded 1x speed?

**Comment by igrigorik** [comment]
Yep, seems reasonable :)

**Comment by truth1ness** [comment]
+1, definitely would like to see this. 

I'm curious, why "r"? "f" seems to make more sense as it's in line with the others and easy to lay one finger on each. Even "w" or "e" would make more sense since you usually keep your three left fingers on the three current keys so these would be a more natural slide up. Personally I think "W" makes the most sense. A S D W is an extremely common key mapping from games to some audio/video applications/etc.

**Comment by ElijahLynn** [comment]
I am neutral, just thought R was convenient and it could stand for 'reset' or 'restore'. R appeared to be free and F on my box (Ubuntu) is already reserved in YouTube for fullscreen allthough not sure if that is something custom I setup or not. 

Does F affect your YouTube experience?

**Comment by truth1ness** [comment]
Ah. Yes, F is reserved for fullscreen. W is free for me though.

**Comment by hsingh23** [comment]
loads of peoples use vimium here https://vimium.github.io/

**Comment by cocomonk22** [comment]
I also believe there should be a key to reset to 1.0 speed. R would be good since it is close to the existing shortcut keys.

**Comment by igrigorik** [comment]
Added reset functionality in https://github.com/igrigorik/videospeed/commit/42c357804d7ada4ecd3a6e3213495377f1739543. Please give it a try -- you'll have to load it as an "unpacked extension".

**Comment by ElijahLynn** [comment]
Tested, works great, thanks!!
