### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by firefoxic** [igrigorik/videospeed#331]
Please, add WebExtension for Firefox.

**Comment by igrigorik** [comment]
The extension APIs are not 1:1, no current plans to support it for FF.

**Comment by j16180339887** [comment]
@codebicycle 's fork supports Chrome, Opera, Firefox and even Firefox on Android.

Many thanks!

**Comment by gslin** [comment]
Hello @igrigorik,

I know this ticket is quite old, but actually the current codebase (master branch) is actually supporting Firefox with minor changes:

```diff
diff --git a/manifest.json b/manifest.json
index 7d0148d..bc49e03 100755
--- a/manifest.json
+++ b/manifest.json
@@ -11,12 +11,18 @@
     "48": "src/assets/icons/icon48.png",
     "128": "src/assets/icons/icon128.png"
   },
+  "browser_specific_settings": {
+    "gecko": {
+      "id": "{12eacda6-ea12-501a-05e9-6a787452e6b7}"
+    }
+  },
   "permissions": [
     "storage",
     "activeTab",
     "tabs"
   ],
   "background": {
+    "scripts": ["src/background.js"],
     "service_worker": "src/background.js"
   },
   "options_ui": {
diff --git a/src/content/injector.js b/src/content/injector.js
index 9887e41..dbfa4c9 100644
--- a/src/content/injector.js
+++ b/src/content/injector.js
@@ -205,7 +205,7 @@ async function injectUserSettings() {
     // Inject settings into page context via custom event
     window.dispatchEvent(
       new CustomEvent('VSC_USER_SETTINGS', {
-        detail: userSettings,
+        detail: typeof cloneInto === 'undefined' ? userSettings: cloneInto(userSettings, window),
       })
     );
   } catch (error) {
```

The first patch is that `chrome.storage` function in Firefox requires an id, so I generated the UUID value with the following command:

```bash
$ echo -n "videospeed" | md5sum
12eacda6ea12501a05e96a787452e6b7  -
```

The second patch is that `service_worker` is not supported in Firefox, but `scripts` is an equivalent alternative.

The last patch is a security design in Firefox: you cannot inject data into webpage directly, as `cloneInto()` is designed for this:

* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts/cloneInto

I use feature detection instead of browser detection in this case (`cloneInto`).  After this change, src/core/storage-manager.js:72 can access `this._injectedSettings` (in webpage context):

    const merged = { ...defaults, ...this._injectedSettings };

The overall changes look minimal, would you like to publish to Firefox add-on platform?
