### ISSUE TITLE
[Suggestion] Can we please try a pause shortcut?

### ISSUE THREAD

**Issue by s-i-m-s** [igrigorik/videospeed#336]
I can see that a few others have already asked in the past but I'd really like to have this feature.
Youtube is different than most as they use both space and k for pause. After using it a while you learn to use k all the time because it's much more reliable.
Most sites like twitch just use the spacebar resulting in the ever annoying spacebar scroll if the video isn't the item in focus.

However Video Speed Controller works as long as you are on the page even if the video isn't the in focus item (on many sites) so it should be able to replicate youtube's more reliable alternate key usage everywhere else. 
Then there are other sites like mp4upload with no keyboard (AFAICT) shortcuts to pause the video at all space doesn't even work while in focus that this would be wonderful for.

**Comment by canarslan12** [comment]
If @igrigorik assign it to me(and also allow me to do it), I can do this in future

**Comment by igrigorik** [comment]
As I've said before, I'm generally wary of adding more and more shortcuts. Not because I don't like shortcuts (to the contrary), but because we inevitably clash and collide with other site-specific and player-specific shortcuts.

One strategy I could see here, which could satisfy both camps, is:
- Instead of using a frozen list of actions, against which you can assign a hotkey..
- Implement a mechanism where the user can add own shortcuts in options panel: 
  - Click "add shortcut" presents:
     - input box for the shortcut key
     - dropdown of allowed actions — e.g. play, pause, seek, ratechange
        - selecting some actions would inject another "value" box — e.g. value for ratechange.

We can still ship a default set as part of the above, but this allows the user to then define as many shortcuts as they want with as many value variations as they want. For play/pause specifically, I wouldn't ship a default shortcut, but with above mechanism the user could define their own.

WDYT?

**Comment by s-i-m-s** [comment]
I like it.
It sounds significantly more complex to implement than adding it without a default option but it also sounds like it would be way more flexible.

**Comment by russelldavis** [comment]
I'd love to have a pause/play shortcut as well.

@igrigorik as an alternative to your suggestion above, would you be open to an implementation of #291, and the addition of a play/pause shortcut defaulting to unbound? (It would be a quick & easy change, while leaving the door open for something more advanced like your suggestion in the future.)

**Comment by igrigorik** [comment]
@russelldavis yes~ish. As in, that addresses our dilemma of conflicting keys, but it keeps accruing technical debt on our side. Ideally, we'd tackle both at the same time.

**Comment by igrigorik** [comment]
Opened new bug to track this, let's continue there: https://github.com/igrigorik/videospeed/issues/347
