### ISSUE TITLE
Twitch live streams tend to switch to 1.03x speed for no apparent reason

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#358]
As title says, it seems kinda randomly triggered...
Windows 7 64 bit
Chrome 67.0.3396.99 (64 bit)

**Comment by canarslan12** [comment]
It's not random, it's because twitch player wants to reach live stream. We can't do anything about it and we don't want to. Will be closed when @igrigorik see it

On Jul 11, 2018 18:55, evodoc <notifications@github.com> wrote:

As title says, it seems kinda randomly triggered...
Windows 7 64 bit
Chrome 67.0.3396.99 (64 bit)

**Comment by igrigorik** [comment]
^ what @canarslan12 said :)

Closing.
