### ISSUE TITLE
Doesn't work on baltimoreravens.com video player

### ISSUE THREAD

**Issue by evilduck17** [igrigorik/videospeed#363]
Can't access the controller in the top left and it starts the videos without sound

**Comment by igrigorik** [comment]
Indeed. There is some crazy iframe nesting going on there.. not sure where the problem is exactly, but it definitely has something to do with the crazy initialization logic they're using on their site.

**Comment by buybuydandavis** [comment]
Looks like the same issue at dallascowboys.com
It seems like they have a frame that covers the controller when you mouse up to the controller.

Possible work arounds -
Have a default location setting for the controller? 
Have default be the last location used?

Although it's unclear that would work. Keystroke control doesn't work on the page either. Even without moving the mouse so that the top frame doesn't pop up.

**Comment by buybuydandavis** [comment]
Somehow during the intro commercial I got it to work, and it bled into the show. I couldn't repeat it, though.

**Comment by buybuydandavis** [comment]
I loaded the page.
Loaded again.
As the commercial played
Put the mouse up near/in the control
Was able to change the speed with Shift-g

**Comment by buybuydandavis** [comment]
Somehow it worked today initially. But after coming here to report, it's not working again.

Must be some timing thing.
