### ISSUE TITLE
Lost all blacklisted sites with latest update

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#401]
My blacklisted sites have been reset since the extension update today. How can I recover them? I have backups of my Chrome profiles. Is there a file I can get them from?

**Comment by canarslan12** [comment]
I checked code and I don't know why blacklist reset. Sorry for that problem.
you can try this code to see if they are still somewhere. you should use this code at vsc settings page
```
chrome.storage.sync.get("blacklist", function (storage) {
  console.log(storage)
})
```

**Comment by garyking** [comment]
That just returns the current blacklist, unfortunately. I was hoping I could open some database or config file from a Chrome profile backup, to retrieve my previous blacklists from them.

**Comment by canarslan12** [comment]
you can try to open(copy Chrome profile to current) previous one without any internet connection and type this code

**Comment by Eisys** [comment]
Same happened to me. And the 'Remember Playback Speed' option got unticked.

I didn't know the extension had gotten an update so it was really weird that all videos started at 1x all the time.

But there seems to be problems with the remembering of speed in this new version. There are times when I open a video and it starts at 2.5x, which is set as preferred speed. Even though last videos I watched were at 2x. This seems to be somewhat random though, most of the time working normally, but never happened with old version.

**Comment by canarslan12** [comment]
I can reproduce remember speed case in youtube. can you give detailed steps to reproduce it

**Comment by Eisys** [comment]
Ok I finally randomly stumbled upon a way to reproduce the bug.

Video 1; I'm watching at 2x. A bit comes up that I want to watch at normal speed, I hit the reset speed button or manually decrease to 1x. Then from the suggested videos I middleclick/ctrl+click a new video to open in the background. I pause this video or just close the tab.
Video 2; It starts at 1x, I hit the reset button again, which should switch between last used speed and 1x but instead of doing that it goes straight to 2.5x.

I'm not entirely sure how it used to work before the latest update but pretty sure it wasn't like this.

So yeah let's say I watch a bunch of videos at 2x, then listen to a song at normal then close all youtube tabs. Then open one again and go to a video, it's at 1x. I expect the reset button to change it to 2x but it's 2.5x instead.
I THINK there are also times where I've been watching videos at a speed under 2.5x, I go to a video and it starts at 2.5x right away without starting at 1x, but I don't know for sure and can't replicate this. This I also said in my original comment so maybe.

I also just tried changing my preferred speed, made it sth more random, 2.73x and it's all the same except instead of 2.5 it's now 2.73.
