### ISSUE TITLE
The position is on top of where YouTube has placed 3D controls

### ISSUE THREAD

**Issue by getsetbro** [igrigorik/videospeed#41]
The position is on top of where YouTube has placed 3D controls
https://www.youtube.com/watch?v=erftYPflJzQ

**Comment by igrigorik** [comment]
Thanks for reporting this! Honestly, I didn't know such thing even existed (3D controls)... pretty awesome.

Should be fixed in master, and if you're willing you can install it as an "unpacked extension". Otherwise, I'd like to fix a few other things before releasing the next update, so it might take a bit longer.

**Comment by getsetbro** [comment]
Tested. Fixed. Thanks.

**Comment by getsetbro** [comment]
I see now youtube has speeds under settings menu 
![image](https://cloud.githubusercontent.com/assets/442793/7750828/0ca364b4-ff9c-11e4-8ba3-31f1dde31c1d.png)

**Comment by igrigorik** [comment]
@getsetbro that's been there for a while on the HTML5 player. For me, personally, that's insufficient: not enough granularity and the 2x cap is "too slow" :)
