### ISSUE TITLE
Not working on the site Unacademy

### ISSUE THREAD

**Issue by jainronak123** [igrigorik/videospeed#437]
Doesn't work on the website Unacademy. I tried disabling the flash. 
Sample video:
https://unacademy.com/lesson/cop-24-katowice-2018-part-2/BL52OYI3

**Comment by jacobcolbert** [comment]
It doesn't work since they use an audio container and load a new jpg every time the slide changes. This is the same as the feature request in #158. It works fine-ish in my personal version I run with the minimal fix for audio. (One issue is that s and d are already hotkeyed by the player. Also the controller is obscured by the slides.)

**Comment by igrigorik** [comment]
@jacobcolbert thanks for triaging this. 

Closing, let's continue in #158.
