### ISSUE TITLE
Speed reverts when skipping ahead

### ISSUE THREAD

**Issue by Rowsol** [igrigorik/videospeed#455]
It started today. If I load up a video it remembers my speed as it always did. If I change the speed and skip ahead in the video the speed reverts to what it was when I loaded the video.

**Comment by igrigorik** [comment]
Is there a particular site where this is happening for you? I can't replicate so far.

**Comment by Rowsol** [comment]
Youtube is where I first experienced it. Nothing has changed with my setup so I'm at a loss. Here's a snippet. https://youtu.be/XOEbSEAO9UQ

**Comment by WofWca** [comment]
Same stuff happens when you pause-unpause it.

**Comment by WofWca** [comment]
I've reinstalled it, looks like it's working now.
I have some custom buttons (multiple buttons are assigned to reset the speed).

**Comment by WofWca** [comment]
Looks like it only appears when "Remember Playback Speed" is ticked.

**Comment by kdP21** [comment]
Having this same issue. Started happening out of nowhere. Might have began after the latest update. Checking/unchecking "Remember Playback Speed" does not seem to be resolving the issue.

**Comment by web2033** [comment]
Similar to me:

Any mouse click on the video timeline
Enter/Exit fullscreen mode

Sets speed back to 1.00

**Comment by derelse** [comment]
Same as web2033 happens to me. Also when I pause and unpause the speed resets to 1.00. 

Disabling the extension allows me to use the normal YouTube speed options without bugs. 

Just tried again after disabling and enabling the speed controller it seems to work normally if I don't check remember speed... 

 Some months ago I had a similar problem, that was fixed by enabling that option lol
