### ISSUE TITLE
Speed resets when video quality changes

### ISSUE THREAD

**Issue by inian** [igrigorik/videospeed#457]
When the "Remember playback speed" option is unchecked, and when the quality of the video on youtube changes (due to changing network conditions, etc), the video playback speed resets to 1x each time. Does not happen when remember playback speed option is checked, but with the latest update, there is [this issue](https://github.com/igrigorik/videospeed/issues/455#issuecomment-485296516). 

Not sure, if this is the expected behaviour, but I would expect the video speed to remain the same (not reset to 1x) even when the remember playback speed option is unchecked.

**Comment by jacobcolbert** [comment]
Did this happen before the latest update?

**Comment by jacobcolbert** [comment]
I actually can't replicate this bug on any version. Can you say if it happened both before and after today's update?

**Comment by igrigorik** [comment]
@jacobcolbert found a way to reproduce this.. Go on youtube, pick any video, start playing and adjust the speed and then hit the gear icon and select a different quality level: it resets the speed back to last remembered speed when you do this. This is a manual trigger, but I hit the same case when YT auto switches due to network quality.
