### ISSUE TITLE
Speed automatically sets to 1.03

### ISSUE THREAD

**Issue by jwong098** [igrigorik/videospeed#484]
Same issue as #430.
This problem occurs when watching a twitch video. If I have "remember playback speed" turned on, then this 1.03 transfers over to other sites like YouTube as well.

Unfortunately, I can't reproduce this issue with 100% consistency. I find that it occurs more frequently with some video streams vs others; it seems to occur more often on streams that take a while to load. I'm able to reproduce this issue relatively consistently with this link: https://www.twitch.tv/tcec_chess_tv

**Comment by DragonRepairman** [comment]
I am having this issue as well.

**Comment by jacobcolbert** [comment]
This is really weird, but it is a twitch error and I don't really think it makes sense to add code to work around whatever is happening from their end. I turned off VSC and checked the playbackRate of the video and still find that it occasionally goes to 1.29999999.

**Comment by Glaived** [comment]
> This is really weird, but it is a twitch error and I don't really think it makes sense to add code to work around whatever is happening from their end. I turned off VSC and checked the playbackRate of the video and still find that it occasionally goes to 1.29999999.

@jacobcolbert @igrigorik 
**Many people** use your extension to fix the Twitch bug. I understand your positioning regarding the possibility of developing a third-party solution, in a perfect world, it is up to Twitch to fix its bugs.

Nevertheless, Twitch has still not provided a solution despite the months that have passed, so I invite you to consider developing a solution integrated with your extension, or developing a new extension to solve this problem specifically.

🙏🏻

**Comment by MonkWho** [comment]
This issue is still present on twitch, however there is a solution. Extension called FFZ recently added an option "_Allow the player to speed up to reduce delay_" with description "_Twitch, by default, will apply a minor speed up to live video when you have a large delay to the broadcaster in order to catch back up with the live broadcast. This may result in audio distortion. Disable this to prevent the automatic speed changes_".

Guess this explains why sometimes twitch decides to set your speed to 1.03. And with this setting disabled in FFZ it never happens anymore. Hope this helps anyone struggling with twitch breaking Video Speed Controller. IMHO FFZ is a required extension for anyone using twitch in a browser.

**Comment by igrigorik** [comment]
Aha! Thanks for tracking this down. Do you know what logic FFZ is using to disable this behavior?

FWIW, I don't think our extension should be overriding this, more just curious how they're preventing this — guessing, by hijacking or monkey patching one of the internal functions on the player?

**Comment by MonkWho** [comment]
It looks like they play with a variable in the player script. Specifically I think it's controlled by setLiveSpeedUpRate.
