### ISSUE TITLE
Controls hidden (can't unhide) on Reddit, Gfycat, etc, but works on YouTube

### ISSUE THREAD

**Issue by soccerrj88** [igrigorik/videospeed#501]
Problem started with not being able to click controls while browsing Reddit/Gyfs but keyboard shortcuts worked and appeared correct on video. Now the keyboard shortcuts still appear to work, but I can not get the speed/controls to show up on videos/gyfs. Youtube still works properly.
I tried using "H" to show controls, change opacity in settings, and obviously hover over the video. Opening Reddit links to the host website (ex gfycat.com) does not show controls on host website either.

**Comment by mjjones90** [comment]
Are your controls hidden for local files too? The controls are visible for me on Reddit, Youtube, and Twitter but are no longer showing when I play a local mp4 file. I've had "Allow access to file URLs" enabled for a while now and the shortcuts still work, but the controls disappeared for local files within the last week or so.

**Comment by mjjones90** [comment]
I found a workaround for hidden controls on local files. Open the Inspect tool by either pressing Ctrl + Shift + I or right clicking on the page > Inspect. In the Elements tab, expand <body class...> then remove "vsc-nosource" from the line that starts with <div class="vsc-controller vsc-source"...>.

This has to be done each time you open a file. I can't check to see if it works for websites, though, since the controls still show on my end.

**Comment by thewheat** [comment]
I think this could be fixed in the next version since https://github.com/igrigorik/videospeed/pull/529 has been merged

Tested with
- https://gfycat.com/anchoredenchantedamericanriverotter-saturday-exhausted-weekend-kitten-pissed 
- https://www.reddit.com/r/gifs/comments/ddo1ny/you_just_got_april_fooled/

Testing with the code change locally
- the controls show for both 
- but for Gycat clicking it results in the video being paused/played which I believe is this issue https://github.com/igrigorik/videospeed/issues/512

**Gycat**
![image](https://user-images.githubusercontent.com/892961/66263397-e7fb8d00-e824-11e9-8ca3-c824b4233849.png)

**Reddit**

![image](https://user-images.githubusercontent.com/892961/66263454-8982de80-e825-11e9-81e0-3ee8a2bb7e24.png)
