### ISSUE TITLE
Controls don't appear on `livestreamfails.com`

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#514]
Is it possible to make the controls for this extension appear on videos from [this site](https://livestreamfails.com/post/52335)?

**Comment by thewheat** [comment]
I believe this should be fixed in the next version now that https://github.com/igrigorik/videospeed/pull/529/files is merged

Testing that site with my code change allows the controller to show up
![image](https://user-images.githubusercontent.com/892961/66263369-3fe5c400-e824-11e9-8889-4657662a1f99.png)

**Comment by jacobcolbert** [comment]
Thank you @thewheat for this great contribution that fixes so many of these related issues! Tagging #529 for future reference.
