### ISSUE TITLE
Button appears in middle of all embedded Reddit videos

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#536]
I'm referring to videos on Reddit from the domain `v.redd.it`, which are those hosted by Reddit itself.

[Link](https://old.reddit.com/r/funny/comments/dhfigp/irish_man_leaves_funny_recording_for_his_funeral/) to test with.

[Sample screenshot](https://user-images.githubusercontent.com/343940/66867504-6fee3f00-ef69-11e9-9fbc-1da93258093b.png).

**Comment by thewheat** [comment]
Hi @garyking 👋 thanks for those links and screenshots! 🙌 I've tried this on my end but I'm not experiencing the same problem: it all works as expected 🤔

![image](https://user-images.githubusercontent.com/892961/66921995-c8e8d080-f058-11e9-88ec-3bf6efbe7a3c.png)

From this other issue https://github.com/igrigorik/videospeed/issues/449 there was mention of a possible conflict with the Reddit Enhancement Suite extension
- I tried installing it myself and the controller still appears as per normal.
- Could you perhaps disable any other extension one by one via chrome://extensions/ and reload the page to see if you can identify which one it conflicts with? 

![image](https://user-images.githubusercontent.com/892961/66921889-9b038c00-f058-11e9-9c9f-532f94f03493.png)

**Comment by Eisys** [comment]
I experience the same thing.
I also have RES but the issue still appears with every single extension other than VSC disabled.

Chrome 78. Win 10 1803.

**Comment by garyking** [comment]
I don't have RES. This issue has existed in this extension for months; probably since Reddit introduced embedded videos.

**Comment by garyking** [comment]
Okay here are some updates.

I tested this issue in a new Chrome profile. 

The issue does not exist on the new Reddit layout. It only exists on the old one. [Here's a link to a video on the old Reddit layout.](https://old.reddit.com/r/funny/comments/dhfigp/irish_man_leaves_funny_recording_for_his_funeral/) The URL just needs to start with `old.reddit.com`. VSC cannot be clicked on, or moved, in the old layout. Screenshot with red box:

![Old Reddit](https://user-images.githubusercontent.com/343940/67515088-f55da780-f66b-11e9-8701-2e7fe0afe301.png)

On the new Reddit layout, there are two VSC buttons. That one (as seen in the red box, below) I think is for the preview that appears when you hover over the video scrubber. Would be nice if that one didn't appear.

![New Reddit](https://user-images.githubusercontent.com/343940/67515164-1cb47480-f66c-11e9-9f65-bca77d44f26b.png)

**Comment by ChadBailey** [comment]
I also experience this behavior on the old version of reddit and not the new just as you describe.

I do not, however, experience the bug of the secondary speed indicator below the seek bar. I suspect it may be due to a secondary video element somewhere, like an advertisement.

**Comment by thewheat** [comment]
Thanks for the link showing the video with the issue @garyking 👍 I am able to see the problem myself with the controller showing in the middle of the video and it looks to be due to a CSS `transform` on the video element :\
- Removing it shows that the controller is correctly placed in the top left of the video
- The solution would probably be to identify actual position of the element after the CSS transform. If that doesn't work or is not possible I think a custom CSS based on URL could be used if that is something we'd want to support 

![image](https://user-images.githubusercontent.com/892961/68200516-08249480-fffb-11e9-86e3-885b6f2c6df6.png)



Regarding the other controller showing at the bottom of the page. I'm not able to see it but if I hover over the play timeline there is a thumbnail of the video which does show a controller
![image](https://user-images.githubusercontent.com/892961/68200397-bda31800-fffa-11e9-80c1-046d3b86351a.png)

**Comment by ChadBailey** [comment]
I'd really like to get this fixed as it's an older issue, but not sure I fully understand it. If someone else wants to take it on feel free, otherwise I have it slated for me to investigate and potentially include in 0.7 release

**Comment by igrigorik** [comment]
Looking at the latest version of Reddit, I _believe_ this is no longe an issue -- hooray! I see the button showing up correctly on all the videos.
