### ISSUE TITLE
will AppleTV+ work in the future?

### ISSUE THREAD

**Issue by sidgestion** [igrigorik/videospeed#540]
can't tell if they're using HTML5, but it doesn't work currently

**Comment by mariusi7** [comment]
Logged in to post exactly this. Please, please check if there's any hope!

**Comment by ChadBailey** [comment]
I don't have access to the service to check, but you can check for yourself if you like. Just right-click on the video and click "inspect element" then find out if it is tagged using <video>.

If a custom right click menu prevents you from doing this, you can open Chrome's inspector via Ctrl+Shift+I (capital i). Once it's open, click the little mouse cursor in the top-left corner of the inspector then highlight over the video and click.

![image](https://user-images.githubusercontent.com/15102816/68066487-db286700-fd06-11e9-985f-3b0dec7bee69.png)

**Comment by sidgestion** [comment]
<body class="ember-application vsc-initialized" style="overflow: hidden;;/*startDM*/background-color: #222222 !important;color: #eeeeee !important;/*endDM*/;/*startDM*/background-color: #222222 !important;color: #eeeeee !important;/*endDM*/">

Was this correct?

**Comment by sidgestion** [comment]
<img width="547" alt="Screen Shot 2019-11-02 at 1 45 48 AM" src="https://user-images.githubusercontent.com/29824742/68066693-8be83380-fd12-11e9-95b7-c265d64b66d0.png">

**Comment by sidgestion** [comment]
The service is at tv.apple.com. The trailers are there without needing a subscription, if that helps.

**Comment by mariusi7** [comment]
@ChadBailey  
Yes, they are, e.g. for the free trailer from this page:
https://tv.apple.com/us/show/see/umc.cmc.3s4mgg2y7h95fks9gnc4pw13m

<video id="apple-music-video-player" title="null - " src="blob:https://tv.apple.com/e398c722-ad58-44ee-9c82-c82974a5573a"></video>

**Comment by mariusi7** [comment]
But:
document.getElementsByTagName('video').length = 0
document.querySelectorAll('video').length = 0
The addon relies on getElementsByTagName('video'), so I think for some reason it can't find it in the DOM...

**Comment by mariusi7** [comment]
@igrigorik , @jacobcolbert any idea ?

**Comment by mariusi7** [comment]
The player is HTML. If I stored the video tag as global variable, I could use it fine in temp.playbackRate = 3; and the speed changed. So we would only need to detect the video..

**Comment by ChadBailey** [comment]
Thanks for those details... I was also able to reproduce by finding a trailer there. I may take a stab at fixing this one, unless you're already working on it @mariusi7 .

**Comment by jedawson** [comment]
![image](https://user-images.githubusercontent.com/20781285/68072997-ea84d000-fd59-11e9-87c9-404da48eea64.png)
I see that the video tag is nested in a bunch of shadow DOM's. When a video plays, the page adds in the src attribute. When the page first loads, i don't see vsc adding in a vsc-nosource tag, which means that the first MutationObserver isn't going through the shadow DOM. So, I'm assuming that the issue is with the first MutationObserver rather than the second MutationObserver. But just looking at the source, it looks like the page doesn't load the shadow DOM initially. So, the second MutationObserver would have to be aware of the shadow DOM after it loads, and then the first MutationObserver would have to be aware of the src change when a user clicks on a video to watch. there's an old stack overflow question about this but i don't see how the answer is helpful. https://stackoverflow.com/questions/24486923/mutationobserver-and-shadow-dom

**Comment by jedawson** [comment]
it looks like another project has implemented a shadow dom mutation observer
[https://github.com/medialize/ally.js/pull/114/commits/a53a4df64d01612f6d3fff93d09425771597a495](url)

**Comment by mariusi7** [comment]
@ChadBailey I'm not, it's out of my skills.

**Comment by jedawson** [comment]
`document.getElementsByTagName('apple-tv-plus-player')[0].shadowRoot.firstChild.getElementsByTagName('amp-video-player-internal')[0].shadowRoot.firstChild.shadowRoot.firstChild` will get the div tag element that holds the video tag element. 
the div tag element is `<div class="video-container" id="video-container"><video id="apple-music-video-player" title="The Elephant Queen - " src="blob:https://tv.apple.com/this-is-a-video-UUID"></video></div>`
the video tag element gets added as a child element once play episode button is pushed. 
can the second mutation observer just observe this div tag element? maybe something after this line https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L429

**Comment by ChadBailey** [comment]
@jedawson thanks for sharing those details. This may also be beyond my skill level. I've never worked with a shadow DOM before. Full disclosure I don't normally work in JavaScript which is partially why I decided to try picking up some bugs in this project.

When trying to manually select the video element then adjust the `playbackRate` property, I found I could not select it using `document.getElementsByTagName`

```JavaScript
> document.getElementsByTagName("video")
<- HTMLCollection []
```
When working with iframes, I recall being able to "enter" that iframe then select, but my searches for a similar behavior in a shadow DOM came up nill. I was able to write a function to capture all shadowroots, but I wasn't really able to progress past that.

```
  function getShadowRoots() {
    shroots = [];
    for (let el of document.getElementsByTagName('*')) {
      if (el.shadowRoot) {
        shroots.push(el);
      }
    }
    return shroots;
  }
```

When I first tried this, I thought it wasn't working correctly because it was only getting 2 shadow roots. I discovered that was due to it being unable to search within those to discover subroots.

```JavaScript
> getShadowRoots()
<- (2) [amp-mediakit-root.hydrated, apple-tv-plus-player.hydrated]
0: amp-mediakit-root.hydrated
1: apple-tv-plus-player.hydrated
[]: (...)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 2
__proto__: Array(0)
```

Taking a completely different approach, I rationalized based on @jedawson's comments that the existing logic may be working perfectly fine as is, but not initialized due to the way videos are loaded after VSC was initialized.

To test this I tried putting the initialization on a timer, but unsurprisingly didn't observe a difference. I imagine this may be due to some protection in VSC to not double-initialize, but can't be sure.

**Comment by ChadBailey** [comment]
@jedawson it's as if you were reading the future of me posting that post haha. Thanks for detailing how to select, I may actually be able to make some progress now

**Comment by jedawson** [comment]
i tried the video selector in firefox, but it didn't work because firefox adds a style tag element to each of the shadow DOM's. here is the new selector that works in both chrome and firefox
```document.querySelector('apple-tv-plus-player').shadowRoot.querySelector('amp-video-player-internal').shadowRoot.querySelector('amp-video-player').shadowRoot.querySelector('#video-container')```

**Comment by jedawson** [comment]
@sidgestion If you want to change the video speed on tv.apple.com, you can start playing the video, go to the Developer Tools, enter the following into the console log (replace 2 with whatever speed you want, maybe 3 if you drink a lot of ☕️ coffee. haha 🤪):
```document.querySelector('apple-tv-plus-player').shadowRoot.querySelector('amp-video-player-internal').shadowRoot.querySelector('amp-video-player').shadowRoot.querySelector('#video-container').querySelector('video').playbackRate = 2```

**Comment by sidgestion** [comment]
@jedawson would you judge me if I said that 2.7 is normal for me??

Thanks for the tip. This worked

**Comment by ChadBailey** [comment]
Great work, I should have all the pieces I need to get an implementation together. Working on creating a way to implement this generically in hopes of making it robust enough to work for less common video sites that follow a similar design paradigm. No promises on if/when though lol.

If anyone else wants to work on this one go right right ahead, my feelings wouldn't be hurt :P

**Comment by ChadBailey** [comment]
> @jedawson would you judge me if I said that 2.7 is normal for me??
> 
> Thanks for the tip. This worked

Consider yourself judged LOL. Depends on content for me, but 2.7 isn't terribly far off of my typical rate

**Comment by ChadBailey** [comment]
It would appear I'm stuck, and likely due to something embarrassingly simple as is typically the case lol. I'm struggling to debug this effectively since I know very little about debugging JavaScript in a browser. If anyone has any tips feel free to mention them, but shelving this for my sanity for now. Here are the details

I was at least able to validate that the way VSC attaches to video objects does not actually discover videos within a shadowRoot. 

I discovered this by looking at [line 434 of inject.js](https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L434) it assigns all video tags to an array via `var mediaTags = document.querySelectorAll('video');`, then instantiates a new instance of videoController for each of them
```JavaScript
      forEach.call(mediaTags, function(video) {
        video.vsc = new tc.videoController(video);
      });
```
However, `document.querySelectorAll('video');` does not discover video tags within shadowRoots.

```JavaScript
> document.querySelectorAll('video');
<- NodeList []
length: 0
__proto__: NodeList
```

I logically broke this down into 2 steps, 1) create method that works for attaching to videos within a shadowRoot and 2) monitor the DOM for new shadowRoots, then rerun initialize. I have not reached step 2 yet.

I've created this beautiful function (somewhat sarcastic), which ALMOST works lol

```JavaScript
function getShadowRoots(shadowRootElement) {
  shadowRootElements = [];
  contexts = [];
  if (typeof(shadowRootElement) === "undefined") {
    contexts.push(document);
  } else if (shadowRootElement.shadowRoot.children) {
    for (let i = 0; i < shadowRootElement.shadowRoot.children.length; i++) {
      contexts.push(shadowRootElement.shadowRoot.children[i]);
    }
  } else {
    throw('Supplied shadowRootElement is not a valid shadowRoot')
  }
  for (let context of contexts) {
    for (let el of context.getElementsByTagName('*')) {
      if (el.shadowRoot) {
        shadowRootElements.push(el);
        // Recursive check for sub-shadowRoots
        if (el.shadowRoot.children) {
          shadowRootElements = shadowRootElements.concat(getShadowRoots(el))
        }
      }
    }
  }
  return shadowRootElements;
}
```

The issue I'm running in to is it seems to fail at finding all sub-roots. For example, the shadowRoot `amp-video-player-internal` makes an appearance as a member at index 3, but the sub-shadowRoot of `amp-video-player` does not.

```JavaScript
> getShadowRoots()
<- (16) [amp-mediakit-root.hydrated, apple-tv-plus-player.hydrated, amp-playback-controls-exit.hydrated, amp-video-player-internal.hydrated, amp-rating-overlay.ratings-overlay.hydrated, amp-playback-controls-progress.none.hydrated.is-playing, amp-volume-control.hydrated, amp-airplay-control.footer__control.unsupported.hydrated, amp-playback-controls-skip.footer__control.none.hydrated, amp-playback-controls-play.none.hydrated, amp-playback-controls-skip.footer__control.none.hydrated, amp-audio-tracks-control.footer__control.hydrated, amp-captions-control.footer__control.hydrated, amp-playback-controls-full-screen.footer__control.hydrated, amp-skip-intro.hydrated, amp-up-next.hydrated]
0: amp-mediakit-root.hydrated
1: apple-tv-plus-player.hydrated
2: amp-playback-controls-exit.hydrated
3: amp-video-player-internal.hydrated
4: amp-rating-overlay.ratings-overlay.hydrated
5: amp-playback-controls-progress.none.hydrated.is-playing
6: amp-volume-control.hydrated
7: amp-airplay-control.footer__control.unsupported.hydrated
8: amp-playback-controls-skip.footer__control.none.hydrated
9: amp-playback-controls-play.none.hydrated
10: amp-playback-controls-skip.footer__control.none.hydrated
11: amp-audio-tracks-control.footer__control.hydrated
12: amp-captions-control.footer__control.hydrated
13: amp-playback-controls-full-screen.footer__control.hydrated
14: amp-skip-intro.hydrated
15: amp-up-next.hydrated
```

I'm able to manually traverse from this point using
```JavaScript
> getShadowRoots()[3].shadowRoot.children[0].shadowRoot.children[0].getElementsByTagName('video')
<- HTMLCollection [video#apple-music-video-player, apple-music-video-player: video#apple-music-video-player]
HTMLCollection [video#apple-music-video-player, apple-music-video-player: video#apple-music-video-player]
0: video#apple-music-video-player
length: 1
apple-music-video-player: video#apple-music-video-player
__proto__: HTMLCollection
```
Just seem to be struggling to understand where the bug is that's preventing these sub-shadowRoots from appearing in the list generated by `getShadowRoots()`

**Comment by kerafyrm02** [comment]
This should give you what you're looking for:

```
(() => {

const getTags = ($root) => {
    if (!$root) return;

    const $children = Array.from($root.children);
    const hasShadow = $root.shadowRoot;

    if (hasShadow) {
        return Array.from($root.shadowRoot.children)
            .map(($child) => [$child, getTags($child)]);
    } else {
        return $children.map(($child) => [$child, getTags($child)]);
    }
};

console.log(getTags(document.querySelector('body > amp-mediakit-root > apple-tv-plus-player')));

})();
```

Enjoy.

**Comment by jacobcolbert** [comment]
Thanks all for your work on this. Obviously this seems like an important feature site to get working given the activity here! 

@ChadBailey you were almost there. I modified it a bit and now it seems to work. The issue was that you never actually checked whether the direct descendant of a shadowRoot also had a shadowRoot. 

```function getShadowRoots(shadowRootElement,) {
  shadowRootElements=[];
  contexts = [];
  if (typeof(shadowRootElement) === "undefined") {
    contexts.push(document);
  } else if (shadowRootElement.shadowRoot && shadowRootElement.shadowRoot.children) {
    for (let i = 0; i < shadowRootElement.shadowRoot.children.length; i++) {
      contexts.push(shadowRootElement.shadowRoot.children[i]);
    }
  }
  for (let context of contexts) {
	if (context.shadowRoot) {
		shadowRootElements.push(context);
        // Recursive check for sub-shadowRoots
        if (context.shadowRoot.children) {
          shadowRootElements = shadowRootElements.concat(getShadowRoots(context.shadowRoot,shadowRootElements))
        }
    }
    for (let el of context.getElementsByTagName('*')) {
      if (el.shadowRoot) {
        shadowRootElements.push(el);
        // Recursive check for sub-shadowRoots
        if (el.shadowRoot.children) {
          shadowRootElements = shadowRootElements.concat(getShadowRoots(el))
        }
      }
    }
  }
  return shadowRootElements;
}```

The question now is what do we do once we've found all the shadowRoots. We could presumably initialize VSC on all of them, but that could be unwieldy? We would presumably also have to set up a MutationObserver to check for new ShadowRoots. 

There is also the question of best practices regarding ShadowRoots that I am not familiar with. It seems that the whole point of ShadowRoots is to seperate contexts. Explicitly violating that seems like it could lead to issues if a web component has a video/audio tag in it for some reason. Not sure how unlikely that is to be/what best practices are here. Any more experienced webdev people have thoughts? @igrigorik

**Comment by ChadBailey** [comment]
@jacobcolbert truly, I'm just here to learn and support a project I enjoy using. This happens to be the bug that I landed on that's all haha.

Thanks for the updated code. My intent was to look for the `video` tag within all shadowroots, and only if it was present would I initialize VSC. I don't think this would be too unwieldy, but perhaps I'm mistaken.

> There is also the question of best practices regarding ShadowRoots that I am not familiar with. It seems that the whole point of ShadowRoots is to seperate contexts.

Best I can tell, the true intent of this separation is for CSS styles. I would tend to agree if this were a website development effort, but in the context of a plugin it seems fine to me *shrugs*. My thoughts are that in order for this plugin to always be able to work, it must be able to find all audio/video tags regardless of where they are within the DOM. After all, in an ideal world if it's a video anywhere in the browser the speed should be controllable.

**Comment by jacobcolbert** [comment]
Yeah, that is me too lol. I didn't know javascript until my first few commits here, and still don't know best practices very well.

> My intent was to look for the video tag within all shadowroots, and only if it was present would I initialize VSC. I don't think this would be too unwieldy, but perhaps I'm mistaken.

That would not be unwieldy but has potential timing issues. If a video tag is created after your sweep, we get nothing. Even 18 mutationobservers shouldn't be a real performance drag afaik, but not sure how high the number of open shadowroots per page reasonably goes. 

And yeah, I'm certainly not concerned about targeted ignoring of scoping, we do worse with iframes already. But a broad spectrum invasion that seems necessary for a general solution worries me until someone allays my fears.

Please keep going with this. Would be good to have a proof of concept and can see how widely the problem can be solved with your less intrusive approach!

**Comment by ChadBailey** [comment]
> not sure how high the number of open shadowroots per page reasonably goes.

I've actually never seen them at all until now, but man have they ever gone crazy with them, 18 is plenty.

With your help, I seem to have solved 1/2 concerns. The only thing left now is to figure out how to get it to initialize correctly. With this latest commit changing the speed is far easier...

```JavaScript
getAudioVideoElements()[0].playbackRate = 2
```
works within the console now - assuming you've swapped your source from top to video speed controller of course

**Comment by ChadBailey** [comment]
Alright, I think I've taken this bug about as far as I can take it. VSC _should_ now correctly function on videos found within shadow DOM elements. It also seems to use negligible system resources.

It does not yet work on AppleTV+, however... unfortunately. This is because when VSC is first initialized, the video element does not exist on the page. In order to accomplish this, we need to rewrite [initializeNow()](https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L325) and [checkForVideo()](https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L390) in a way that it will be shadow root aware. Currently it depends upon the existence of a body tag and since shadow roots don't (necessarily) have a body tag within them the current implementation would just immediately return without doing any work.

I feel this code is probably good to be pulled in even though it does not fix AppleTV+ specifically, but before it's ready the TODO item does need to be addressed
```
    //TODO: Properly concat both nodeLists or refactor calling routine to
    // allow the use of an array. i.e. Array.from(querySelectorAll('video'))
    // alternately, could just pass an array of nodelists then iterate over
    // them in the calling routine
```

If anyone can come in and help finish the implementation that'd be fantastic.

**Comment by jedawson** [comment]
Also apple tv plus might change a lot because to me the website seems half-baked. there's so many issues like the color temperature changing when subtitles appear, each subtitle language being replicated four times or more in the subtitle dropdown menu, the episode carousel left/right arrows not working when clicked (only two finger drag works) [on 11/6 it appears to have been fixed], the next episode not auto-advancing when the episode ends (along with no next episode preview even though there is an html tag amp-up-next), no preview thumbnail when scrubbing across the timeline, the episode not starting again at the place when last stopped at [on 11/6 it appears to have been fixed], the spacebar keybinding fires both the pause event and the last clicked event (e.g. after pressing the on screen pause button and then pressing the spacebar results in the video being paused and then immediately starts playing again), no skip intro button (even though there is an html tag amp-skip-intro), and when exiting from full screen, there's this swipe transition (from the home page to the video again) that shouldn't be there.

Thanks for listening to my rant, now onto the task.

vsc also uses shadow roots to attach the UI elements to the video, so any function would need to make sure that the recursive call won't become an infinite loop. 
vsc also will only run the initializeNow function once when the document.readystate is complete. I set a breakpoint on the initializeNow function and then reloaded the tv.apple.com website. The shadow roots were not present in the apple-tv-plus-player tag element yet; specifically, the shadow roots are present but have no children yet. So, modifying the initializeNow function to call the getShadowRoots function won't work. mutationObservers are needed instead. 

One implementation might be to make the initializeNow function get the shadow roots and attach the shadow root mutationObserver to them. The shadow root mutationObserver needs to look for shadow root creation and then recursively attach the shadow root mutationObserver. This means that the shadow root mutationObserver will be attached to each node. I'm looking at the ally.js project's implementation, and it seems like that is how they're doing it. Since this means a lot of mutationObservers, maybe this function could only be run on the apple-tv-plus-player tag element. 

Another implementation would be using a timer. Using a recursive mutationObserver will be better than just setting a timer then running getShadowRoots because we don't know the minimum time taken for the shadow roots to populate on all the computers in the world. Computer processing speed and internet connection speed are different for everyone.

PSA - remember to cancel your one week trial tonight so you won't get fined five dollars a month.

**Comment by ChadBailey** [comment]
thanks for the detailed explanation... i may take another stab at it this weekend

**Comment by jedawson** [comment]
ok this kinda works. https://github.com/jedawson/videospeed/tree/apple-tv-plus
it finds the video and attaches the controller but the keybindings don't work, and the controls can't be accessed when you mouseover the video but the controls appear when you mouseover to the vsc controller and wait for the apple tv player to close its own controls.

**Comment by ChadBailey** [comment]
nice! thanks for your hard work on it... going to clone it and mess around with it. if i can find a way to resolve any of the bugs i'll submit a PR to your fork

**Comment by ChadBailey** [comment]
@jedawson i was able to clone your branch and reproduce the effects you pointed out.

the controls being under the close button appears to be an intentional design choice in the amp framework. the way it seems to work is it has some z-indexes set in higher order shadow roots so that no matter what all overlays are painted on top of the video shadow root.

i'm going to see if i can hack up a temporary fix for this issue, just to get some forward movement

**Comment by jedawson** [comment]
I created a breakpoint on the keydown event, and then i have stepped through the debugger and it goes through this to return false
```// Ignore keydown event if typing in a page without vsc
          if (!document.querySelector(".vsc-controller")) {
            return false;
          }
```
I guess this means that even though the .vsc-controller class exists on the page, it is inside the nested shadow roots, so the query selector on the document won't find the .vsc-controller class.

**Comment by ChadBailey** [comment]
> it goes through this to return false

That's the issue I was trying to point out in my above post. 

> It does not yet work on AppleTV+, however... unfortunately. This is because when VSC is first initialized, the video element does not exist on the page. In order to accomplish this, we need to rewrite [initializeNow()](https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L325) and [checkForVideo()](https://github.com/igrigorik/videospeed/blob/ec9f3f6d20068efead4029d5b2095cccd0ac1edb/inject.js#L390) in a way that it will be shadow root aware. Currently it depends upon the existence of a body tag and since shadow roots don't (necessarily) have a body tag within them the current implementation would just immediately return without doing any work.

Every reference in VSC is prefixed with `document.` so the functions will need to be rewritten in order to accommodate this (I think...)

I was able to manually manipulate the page to get access to the controls, but clicking them also produces no results (for what I imagine to be the same reason). I didn't previously understand this is how it worked though, perhaps now all we need to do is rewrite those functions to be shadowroot aware for hotkeys to work (IMO higher priority than getting overlay to work).

**Comment by ChadBailey** [comment]
got a first working version! it's a long way from being ready for a PR, but at least it proves the concept

**Comment by jedawson** [comment]
There are two interesting things on this page.
https://developers.google.com/web/fundamentals/web-components/shadowdom#events

> Tips
If the shadow tree is open, calling event.composedPath() will return an array of nodes that the event traveled through.

>If there are multiple levels of shadow DOM at play (say a custom element within another custom element), you need to recursively drill into the shadow roots to find the activeElement:

```javascript
function deepActiveElement() {
  let a = document.activeElement;
  while (a && a.shadowRoot && a.shadowRoot.activeElement) {
    a = a.shadowRoot.activeElement;
  }
  return a;
}
```

**Comment by ChadBailey** [comment]
Great info, thanks for all of your help researching this. Looks like there is plenty of opportunity for refactoring, but for the here and now we seem to have a MVP.

**Comment by jedawson** [comment]
ok. i have completely changed it. it now will 'deeply' look for the video element recursively two seconds after the apple-tv-plus-player appears. it works, but the vsc controller is stacked underneath some elements and the key bindings don't work.

**Comment by ChadBailey** [comment]
Look at [my branch](https://github.com/ChadBailey/videospeed/tree/bugfix/540) mentioned above, it works with keybindings. The z-index issue isn't solved, but I don't know if that's solvable.

**Comment by sidgestion** [comment]
I am amazed by all of you

**Comment by ChadBailey** [comment]
> ok. i have completely changed it. it now will 'deeply' look for the video element recursively two seconds after the apple-tv-plus-player appears. it works, but the vsc controller is stacked underneath some elements and the key bindings don't work.

Do you want to merge my commits into yours and submit a PR? I think partial functionality is worth committing

**Comment by jedawson** [comment]
ok. i have changed it more. i saw that your getShadowRoots, getAudioVideoElements, getSelectorAllRecursive needed some refactoring. so I created getShadowVideo that uses treeWalker. I also modified this check for the vsc-controller class in the keydown event listener rather than getting rid of it all:
```javascript
          if (!document.querySelector(".vsc-controller")) {
            return false;
          }
```
I think it's ready for the pull request.

**Comment by jacobcolbert** [comment]
Alright, thanks folks! I will take a look at this!

**Comment by jedawson** [comment]
Is there a style guide or some other checks that need to be done to get
this approved? Is there any automated testing? How long does it take for
the PR to be reviewed?

**Comment by ChadBailey** [comment]
@jedawson incredible work! Thanks for refactoring those - it was all I could do to get it working at all haha. Excited to see the new version.

Based on what I saw, I don't think there is a style guide that anyone is adhering to. I think it's just up to @igrigorik to peer review and approve/deny

**Comment by igrigorik** [comment]
Hey folks. Quietly watching in the background.. thanks for the great collaboration on this!

Left a few questions in the PR.
