### ISSUE TITLE
Seek Bar again - Only for Facebook Livestream

### ISSUE THREAD

**Issue by nguadien** [igrigorik/videospeed#553]
Hi,

Thank you a lot for your quick reply on my previous issue.
However this is a big challenge in my work, so I'm sorry to bring this up again.

I really appreciate your efforts in making this extension.
What I suggest is a Seek Bar added into this extension's controller panel (which is already present and togglable) exclusively for Facebook Livestreams

As you know, Facebook Livestreams do not have Buffered Bar or Seek Bar to indicate the progress on Buffered Video. Because having to blindly speedup now and then is stressful for my work actually. It exhausts me after 3-4 hours of working.

I really look forward to your reply. Thank you again for your support!

I just thought of a 2nd solution: Option for Auto Speedup
If the extension detects that video is falling behind buffer, it will automatically speedup until it meet the latest buffer, then change speed to 1.00

How about this solution?

**Comment by igrigorik** [comment]
@nguadien thanks for the persistence.. :-)

As a general rule, I do not want to specialize extension for specific players: it makes maintenance an impossible burden and different capabilities on different sites is confusing to users as well. That said, someone building an extension specifically targeting FB and FB capabilities.. makes a lot of sense to me.

> I just thought of a 2nd solution: Option for Auto Speedup
> If the extension detects that video is falling behind buffer, it will automatically speedup until it meet the latest buffer, then change speed to 1.00

That would result in a very jerky user experience: new chunk arrives, we jump up the speed, stall and pause (because we're changing playback speed and messing with buffer estimation algorithms), and repeat over and over.

**Comment by nguadien** [comment]
Thank you a lot for your patience to reply me again with much details. I feel satisfied and I will make do with what I have currently with your extension.

Thank you a gain.
