### ISSUE TITLE
Controller not showing up on Viz.com

### ISSUE THREAD

**Issue by throwaway2342** [igrigorik/videospeed#568]
https://www.viz.com/watch/streaming/media/bleach-episode-4/642

If you try to make the controller show up it appears that it doesn't show up on a website like this

Please fix when possible. 

Info:
I am on a mac and using google chrome--i had this issue for awhile now.

**Comment by ChadBailey** [comment]
I am able to reproduce this, but don't have time right now to find out what's going on.

I am also still impacted by the controller going missing on multiple PC's and the last 5 concurrent bug reports seem to be related to the controller disappearing - #564, #565, #566, #567 (and now this one).

@igrigorik did report this had been fixed in https://github.com/igrigorik/videospeed/pull/567 but not sure if that fix has been pushed out yet. I fear if it has, there may be more work to do *shrugs*

**Comment by thewheat** [comment]
I can't seem to load the video on that page even with a VPN set to US. But I do think it could be related [to the fix Chad mentioned](https://github.com/igrigorik/videospeed/pull/567) which hasn't been released yet as a new version.

If you're willing to test the latest code you can try following these instructions @throwaway2342 to see if that fixes things for now https://github.com/thewheat/videospeed/wiki 🙏

**Comment by throwaway2342** [comment]
I think i will just wait until the pushed out version for now.

**Comment by thewheat** [comment]
New version 0.5.9 has been released @throwaway2342  😃 Hopefully it works now! 🤞
![image](https://user-images.githubusercontent.com/892961/72358477-9c138a80-3727-11ea-856c-4983877ba56d.png)

**Comment by ChadBailey** [comment]
I'm going to assume this has been resolved, if not please open a new issue.
