### ISSUE TITLE
speed controller not showing on first page load

### ISSUE THREAD

**Issue by jorda0mega** [igrigorik/videospeed#572]
I'm using the brave browser and have noticed that the speed controls won't show when I first load a YouTube page. If I click reload they will appear immediately. Has anyone encountered this issue?

**Comment by alon91** [comment]
Same on Chromebook running 79.0.3945.86.

**Comment by Fretice** [comment]
Same

**Comment by nikitabobko** [comment]
Same for Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by WOOB4T** [comment]
Same, Google Chrome Version 79.0.3945.88 (Official Build) (64-bit), Windows 10 Pro 1909, Video Speed Controller Version 0.5.8. Flash is blocked on my chrome://settings/content/flash page.

**Comment by thewheat** [comment]
I think this is the same root issue as https://github.com/igrigorik/videospeed/issues/566 which has been fixed in code but there hasn't been an update to the Chrome web store (so people who have installed it via the web store are still running an old version which has this bug 😞)

I've tested with the latest code on my machine and this issue seems to be solved 😄 

If anybody is willing to test it out, do try loading the latest code by loading an unpacked extension. I have detailed some instructions here https://github.com/thewheat/videospeed/wiki

Alternatively, wait for a new version of the extension to be released 😅

**Comment by WOOB4T** [comment]
@thewheat Yes, using the unpacked extension works perfectly. Thank you!

**Comment by igrigorik** [comment]
Doh! It *was* suppose to release (tagged as v0.5.8.1) but looks like it didn't actually hit the store. Just pushed a new v0.5.9 release.

**Comment by igrigorik** [comment]
Resolving, please reopen if this is still an issue with 0.5.9.
