### ISSUE TITLE
Can the speed of local videos played in chrome be changed?

### ISSUE THREAD

**Issue by SamKaiser2** [igrigorik/videospeed#580]
I have a downloaded video I played in the chrome browser but am not able to use the speed controller.

**Comment by thewheat** [comment]
Hi @SamKaiser2 I believe that is due to some Chrome settings that you'd need to enable

- Go to chrome://extensions (Mac: Window > Extensions. Not sure where it exists on Windows)

![image](https://user-images.githubusercontent.com/892961/72356985-29091480-3725-11ea-86b4-64f8f6112f4e.png)

- Look for **Video Speed Controller** and click "Details"
- Ensure that the `Allow access to file URLs` setting is enabled
- Then reload the tab and you should be good  😃

![image](https://user-images.githubusercontent.com/892961/72356763-c31c8d00-3724-11ea-800a-124f1015e6d4.png)
![image](https://user-images.githubusercontent.com/892961/72356791-cf084f00-3724-11ea-9f64-c6ecb4c5b743.png)

**Comment by ChadBailey** [comment]
@thewheat incredible instructions, thanks for laying this out so well! I think we can close this one since this should fix the issue.

If we ever decide to try and create a wiki/docs this would be a good candidate for inclusion.
