### ISSUE TITLE
JWplayer issue

### ISSUE THREAD

**Issue by shojimeguro** [igrigorik/videospeed#594]
this addon will pause and resume the player on every left click to the controller interface

using shortcut also wont work inside the JWplayer.

you can try them on : https://replay.watch/hydrax.html?vc=1#slug=gDpkbK-c0

**Comment by ChadBailey** [comment]
Thanks for the report. This is due to the same root cause as #589 . I have a detailed explanation there if you want to know more but the short answer is unfortunately this isn't likely to be fixed soon. The good news is the hotkeys do still work as intended meanwhile and I suspect eventually we may get around to fixing
