### ISSUE TITLE
How to handle abuse complaints?

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#597]
I'm concerned that as VSC becomes more popular websites may begin blocking it in order to prevent it being used as a tool for skipping advertisements. I would like to open up the discussion to consider what we could do to provide these websites a better and easier avenue for preventing this abuse than blocking the extension.

What do you all think?

**Comment by jedawson** [comment]
> may begin blocking it

Haven't they already been blocking it (by preventing it from working correctly) on other sites you mentioned like pluralsight?

> preventing this abuse 

I think that any business model accounts for people using services in unintended ways. How are radio stations surviving despite the fact that a lot of people change the channel when an ad comes on?
Also, no one said that Netflix shouldn't have existed when Blockbuster was around. Only the movie studios got angry and prevented them from buying DVDs wholesale. So Netflix just bought DVDs from retailers. This also happened to Redbox. See here: https://nytimes.com/2009/09/07/business/media/07redbox.html


I think this discussion is centered around ad-supported content and does not take into account the needs of people using this for content that they pay for. 

A new argument for the continued existence of this extension could also include "accessibility concerns." 
Read this:
> I'm the blind dev who refactored a huge chunk of the Rust compiler [0]. I'm at roughly 800 words a minute with a synth, with the proven ability to top out at 1219. 800 or so is the norm among programmers. In order to get it we normally end up using older synths which sound way less natural because modern synthesis techniques can't go that fast. There's a trade-off between natural sounding and 500+ words a minute, and the market now strongly prefers the former because hardware can now support i.e. concatenative synthesis.

from
https://news.ycombinator.com/item?id=20883169

Read this: 
> Blind people can easily comprehend speech that is sped up far beyond the maximum rate that sighted people can understand. When we speak rapidly we are verbalizing at about six syllables per second. That hyperactive radio announcer spewing fine print at the end of a commercial jabbers at 10 syllables per second, the absolute limit of comprehension for sighted people. Blind people, however, can comprehend speech sped up to 25 syllables per second. Human beings cannot talk this fast. The scientists had to use a computerized synthesizer to generate speech at this speed. "It sounds like noise," Ingo Hertrich, one of the scientists involved in the research told me. "I can't understand anything…maybe it sounds like some strange foreign language spoken very rapidly." 

from:
https://www.scientificamerican.com/article/why-can-some-blind-people-process/

Blind people have won over web accessibility concerns in the Supreme Court:
https://www.cnbc.com/2019/10/07/dominos-supreme-court.html
Thus, we can conclude that this extension should not be restricted by websites nor can it legally be restricted by websites because blind people need it.

Also, P.S. read this: https://hbr.org/2020/01/advertising-makes-us-unhappy
and if you have time, please read "The Age of Surveillance Capitalism" by Shoshana Zuboff. It is only 692 pages long, but a quarter of those pages are notes/citations.

**Comment by ChadBailey** [comment]
Wow, really cool points you brought up! I do think that this plugin does a very poor job at skipping ads - there are just better ways to do that. Perhaps all of this makes it moot, but I am glad I brought it up as I wouldn't have realized the impact on people like the blind

**Comment by jedawson** [comment]
have you ever heard of betamax case? here is the wikipedia article about it: https://en.wikipedia.org/wiki/Sony_Corp._of_America_v._Universal_City_Studios,_Inc.

also next on the docket we have a case about reverse engineering a product:
https://en.wikipedia.org/wiki/Sega_v._Accolade

up next on the docket is about the legality of cloud DVRs:
https://en.wikipedia.org/wiki/Cartoon_Network,_LP_v._CSC_Holdings,_Inc.

and then a confusingly similar case about the legality of cloud dvd players:
https://en.wikipedia.org/wiki/Warner_Bros._Entertainment_Inc._v._WTV_Systems,_Inc.

and then a disappointing case about the legality of cloud antennas:
https://en.wikipedia.org/wiki/American_Broadcasting_Cos.,_Inc._v._Aereo,_Inc.

also have you heard of the TiVo and Dish saga? 
it is over their patents, and it is sad to see money wasted like this on lawyers for a whole decade. but this is the world we live in. 

and also get ready for the final determination in the fight of locast.org vs the big broadcasters. 
https://www.hollywoodreporter.com/thr-esq/abc-cbs-fox-nbc-sue-locast-a-free-streaming-app-1228244
https://arstechnica.com/tech-policy/2019/09/nonprofit-fights-tv-networks-in-court-to-keep-free-tv-service-alive/

You might be asking why these court cases are relevant. These cases fundamentally concern consumers' rights to do what they want to do with the content that they receive. What is streaming video? Is it a broadcast or is it a temporary copy? These questions may be answered for certain in the future, but what's certain is that the future always changes.

**Comment by ChadBailey** [comment]
I think this has been open long enough to gather the feedback necessary. I'll go ahead and close it out. If anyone reading this has further comments - or you are the owner of a video site and want to add your input - please feel free to reopen or open a new issue
