### ISSUE TITLE
Lagging behind at Videos with 60FPS

### ISSUE THREAD

**Issue by Boebbers** [igrigorik/videospeed#606]
When I watch videos that have a framerate above 30FPS the video gradually lags behind until it freezes for a short time and then it plays normally again. After that it will repeat the process with lagging more and more behind.

The only way that i found to fix it, is to set the video quality down so that the video isnt playing at 60FPS anymore

**Comment by ChadBailey** [comment]
If you remove video speed controller does it go back to normal?

**Comment by Boebbers** [comment]
It only accures when the video is played at higher speed. I usually watch
videos 2x the speed but it also lags behind at other speeds.

But at normal speed everything is fine.

Chad Bailey <notifications@github.com> schrieb am Mi., 4. März 2020, 15:30:

**Comment by Eisys** [comment]
This may or may not be directly related to VSC.

I mostly watch at around 1.5-2x, perhaps 2.5x when a vid is extra slow.

I've been struggling with youtube going out of sync for YEARS.
Mainly when a video was playing in the background for an extended period, once I went back to the tab the video and audio would be out of sync. The longer it was playing in the background, the more it was out of sync.
For a long time, disabling the #disable-accelerated-video-decode flag in Chrome fixed it. 
Perhaps something you could try as well if you're on Chrome.

But more recently(past 4-6 months or sth) YT sometimes goes out of sync anyway, no matter what I do, whether it's playing fore- or background. It's the most annoying shit ever, specially since I watch a lot(way too much) of Youtube.
I have to refresh the page for it be in sync again. Mostly on longer videos, on shorter(less than ~15mins) it doesn't have time to go out of sync enough to notice.

Late last year Youtube started having these sharp sudden crackles in audio, again mostly in the background, This too has happened over the years. The decode flag used to fix the crackles completely but not anymore.
I tried updating all sorts of drivers, etc.. Eventually I reinstalled Win 10. Nothing helps. Idk if it's my PC, Chrome or Youtube fxxking things up.

Right now I'm left with the occasional crackles, and audio sync issues every now and then

Sorry for the long and mostly unrelated rant. It just really pisses me off.

**Comment by ChadBailey** [comment]
I know that the problems you both describe are real, but unfortunately they are completely unrelated to video speed controller and therefore I am closing this. Please feel free to reopen if you experience the problem with video speed controller installed and do not experience it with it removed.

## Further explanation and suggestions

There are many underlying complexities that aren't exposed to the end user at play here, which is why I think it's a little silly that creators use 60fps content for no good reason. Creators should, IMHO only upload at 60fps if there is a true need for it.

The primary issue is there are multiple decoders available (h264, VP8, VP9, AV1, and some others iirc). Depending on your machine, you may have dedicated hardware that for example decodes h264 but nothing for the other codecs. The end result is a dramatic (or traumatic, depending on who you ask) difference between the battery life/playback quality/etc when YouTube uses codecs that your PC has no dedicated hardware decoder for.

You can use a tool like [DXVA Checker](https://bluesky23.yukishigure.com/en/DXVAChecker.html) for identifying which decoders are hardware accelerated on your computer.

One thing you can do is use an extension that forces the default codec - h264 - to be used, thus effectively blocking 60fps playback and giving your playback experience the highest possibility of being able to play back in a smooth way. This open source extension aptly named [h264ify](https://github.com/erkserkserks/h264ify) does just that. There's even [a fork](https://github.com/alextrv/enhanced-h264ify) called enhanced-h264ify which allows you more control over which are being blocked.

Bringing these features into video speed controller is beyond the scope of the project as this has nothing to do with playback rate.
