### ISSUE TITLE
Controller disappears when some mutations occur

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#609]
Formerly: Old controller isn't fully removed (renamed title for clarity)

Steps to reproduce:
1. Install latest version of VSC master branch (last commit is [5a53f81](https://github.com/igrigorik/videospeed/commit/5a53f81cba0091a343ddcaca8a9bad8853c65eb7)) - note that this isn't in the store yet for some reason
2. Visit https://app.pluralsight.com/course-player?clipId=1e8b695e-a148-4b6b-83d0-07c9ddbb9b73
3. Click the settings gear on the bottom-right (speed control box works too, anything that triggers a mutation)
4. This will trigger `MutationObserver` and when it reaches `oldController.remove();` the controller is removed, but only partially.

This line of code should have been executed but doesn't seem to be:
https://github.com/igrigorik/videospeed/blob/5a53f81cba0091a343ddcaca8a9bad8853c65eb7/inject.js#L220

Also, no errors to speak of, and breakpoints for some reason aren't triggered, but the controller does in fact get removed.

5. `checkForVideo` is then executed which in turn executes `node.vsc = new tc.videoController(node, parent);`
https://github.com/igrigorik/videospeed/blob/5a53f81cba0091a343ddcaca8a9bad8853c65eb7/inject.js#L516
6. Finally, on line 125 it checks for "vscid" which it finds because `oldController.remove();` didn't complete all of its instructions on step 4 and the new video controller is never generated:
https://github.com/igrigorik/videospeed/blob/5a53f81cba0091a343ddcaca8a9bad8853c65eb7/inject.js#L125

Workaround: comment out `oldController.remove();` on line 514:
https://github.com/igrigorik/videospeed/blob/5a53f81cba0091a343ddcaca8a9bad8853c65eb7/inject.js#L514

**Comment by cristiancundari** [comment]
This happens because of this check on videoController object creation:

https://github.com/igrigorik/videospeed/blob/884be009a45b80a2ea95ac28391c4e2b53e220bd/inject.js#L156-L158

When the oldController get removed, the vscid data attribute on the video node will not.

It can be solved by deleting the previous instance of vsc from DOM video element; simply by adding this code

```javascript
if (node.vsc) {
  delete node.dataset.vscid;  
  delete node.vsc;  
}
```

after `oldController.remove();` on line 602:

https://github.com/igrigorik/videospeed/blob/884be009a45b80a2ea95ac28391c4e2b53e220bd/inject.js#L601-L603

**Comment by ChadBailey** [comment]
Thanks so much for the explanation and fix! Feel free to open a PR of your own if you like, otherwise, I'll get these changes in as soon as I can.
