### ISSUE TITLE
Add support for Apple TV+

### ISSUE THREAD

**Issue by pedantique** [igrigorik/videospeed#610]
You can view Apple TV+ in Chrome at https://tv.apple.com/. I'm assuming it is HTML5, but VSC doesn't seem to work.

Any thoughts?

**Comment by ChadBailey** [comment]
This has been fixed (see #540 ), but the latest build has not been uploaded to the chrome store yet. Maybe @igrigorik can make that happen? I'd be glad to do it directly, but I'm not sure how to properly do that.

**Comment by jedawson** [comment]
i forgot to tag the release. i'll add a new commit and then tag it.

**Comment by pedantique** [comment]
Thanks! 0.6.0 does seem to work (although the controller doesn't seem to appear, but I think [#540](https://github.com/igrigorik/videospeed/issues/540) refers to that).

In the meantime, I found these [instructions](https://www.mattcutts.com/blog/how-to-install-a-chrome-extension-from-github/) handy for sideloading the latest GitHub version of the extension into Chrome.

**Comment by ChadBailey** [comment]
I'm not sure about the others, but I don't personally have a subscription to apple tv. Could you test the latest version and confirm if it's working on the "real" site for us? I'd love to know more, and if the controller is showing up or not. The controller not appearing _could_ be related to #609 but I have no idea.

I know that I just tried with the latest version on my own branch and did observe the controller not being visible as you say. It's possible that the controller does exist, but is in a nested shadowroot making it impossible to be visible due to the architecture issues I pointed out in #589

**Comment by pedantique** [comment]
I have tested again cannot see the controller on Apple TV+. Hitting the hotkey does not help.

**Comment by ChadBailey** [comment]
Thanks for the report. I'll see if I can take a closer look to see why this is happening

**Comment by jedawson** [comment]
the reason why it doesn't work is because the apple incorporated put the aria-hidden attribute behind a shadow root. it's all a game of cat and mouse. now the mouse needs to find a laser pointer to distract the cat.

**Comment by jedawson** [comment]
and it's also because they added in autoplaying video previews.

**Comment by pedantique** [comment]
One product idea I had that may deal with this issue of the controller disappearing is if VSC could support the MacBook Pro touch bar either natively or via [Better Touch Tool](https://folivora.ai/). Clearly, that would be a OS X only solution. Has anybody considered this?

**Comment by ChadBailey** [comment]
I've heard rumors the new macbooks may stop having the touch bar... https://www.digitaltrends.com/computing/apple-macbook-pro-without-touch-bar-2019-improved-feature/

However, if you or someone else wanted to implement something like that I certainly wouldn't be opposed... that obviously would not take priority over fixing it for everyone though.

I know of several ways we can pull this off (I detailed some ideas in #589 ), but it all begins with refactoring so that the controllers are in a more structured data model that can be placed outside of any container. The problem with the current implementation is that once a controller is nested inside of something (iframe or shadowroot), the parent document can always cover them. Once they are planted in a shared div at the document root they can be treated equally with the rest of the contents.

This honestly feels like a shortcoming of the extension API as an extension should have higher level control of visibility than the DOM itself IMO. It would be really nice to just be able to do something like `chrome.overlay = true` and no longer have to think about competing with the browser space. While I'm at it, I'll also go ahead and say that the best possible design would make the website completely unaware of the extension rather than having to taint the state of the website itself with injected scripts.

**Comment by jedawson** [comment]
If I were pedantic, I would say that it's not the right place to recommend a new feature to fix an issue in the comments of an unrelated issue. It's akin to asking the plumbers to add in another toilet in the bathroom while they're currently fixing the toilet. Since I'm not pedantic, I'm not going to say that.

**Comment by jedawson** [comment]
How is Chrome doing this: https://www.blog.google/products/chrome/manage-audio-and-video-in-chrome/
?
If there is a media hub that can sense what is playing, it could be possible to use that same feature to add in the vsc controller to currently playing things, rather than looking for video tag elements.

**Comment by jedawson** [comment]
https://stackoverflow.com/questions/59838956/chrome-media-hub-api

**Comment by ChadBailey** [comment]
i like it, and would love to use it for this purpose if we can... but i do think we also need to solve for the controller visibility since it's currently the only option available in fullscreen. that said, i don't see why we couldn't do both. my thought is to have an object model that is at its root a list of controller objects so it could be enumerated. for example (pseudo-code):

```javascript
var controllers = [];
forEach.call(mediaTags, function(video) {
    video.vsc = new tc.videoController(video);
    controllers.push(video.vsc);
});
```

**Comment by ChadBailey** [comment]
These changes have been pushed to the chrome web store! Can I have you try it out now?

**Comment by ChadBailey** [comment]
> I have tested it again and cannot see the controller on Apple TV+. Hitting the Show controller hotkey does not help.

If this issue remains (I expect it to), it is now issue #609 - but please do advise if you're able to use on appletv with the latest version from the chrome web store

**Comment by pedantique** [comment]
> please do advise if you're able to use on appletv with the latest version from the chrome web store

Speed control working on AppleTV+! (And, yes, the controller does not show). Thanks!
