### ISSUE TITLE
New Feature, maybe?

### ISSUE THREAD

**Issue by michelkdev** [igrigorik/videospeed#631]
Hi, Have you thought about putting a video time calculator? For example, if I choose the 1.5x option on a youtube video, I could return a new estimated time when I would finish watching that video. For example, in a 10 min video, with 1.5x speed it would take approximately 7min to watch, this could be placed under the speed frame. This would help a lot and maybe users will be more excited to force themselves to watch the videos more and faster. And it helps a lot to plan when it comes to watching many videos on youtube.

Thanks.
![Untitled-1](https://user-images.githubusercontent.com/5290705/78412532-10085500-75ea-11ea-9e27-c725511cf2fe.png)

**Comment by ChadBailey** [comment]
i love this idea, but i think i would elect to simply put the time remaining under the speed

for example, say you have a 10 minute video, you're at 5 minutes and you have the playback speed at 2, this is what you might see:

```
2.0
-2:30
```

or 1.5x (assuming my quick mental math is right)
```
1.5
-3:45
```

**Comment by Kricheldorf** [comment]
I started coding @ChadBailey suggestion. I've added the option to show the remaining time on the settings page, so the user has to enable this option to get it working. 

You can see how it is looking like in the screenshots below (any visual improvement suggestion is appreciated):
![image](https://user-images.githubusercontent.com/5922387/80296015-1358b180-874e-11ea-9310-62896194b9d5.png)
![image](https://user-images.githubusercontent.com/5922387/80296017-15227500-874e-11ea-8ea6-bcb90f62185d.png)

I have a problem that I want to share with you before I open a PR.
I believe we would need to use setInterval to check the video currentTime every second or use some sort of event listener for that.
Since I don't fully know the constraints of this project, I wanted your opinions on that. I don't feel like a setInterval is a good option, especially if it will be run on every page that has a video for every video the page has. What do you think?

**Comment by igrigorik** [comment]
Related discussion: #692. Let's continue there.
