### ISSUE TITLE
Audio not synced with video

### ISSUE THREAD

**Issue by kurtjohnson0** [igrigorik/videospeed#660]
The audio is sped up but the animation is still at normal speed.

**Comment by MajinBui** [comment]
Can you please provide more details?  e.g. which website you were trying?  This might have been fixed as part of the 0.6.2 branch but has not gone live yet.

**Comment by kurtjohnson0** [comment]
https://training.ctsys.com/cts/CompanyUsers/index.cfm?event=Common.ViewLogin

Sent from Mail for Windows 10

**Comment by igrigorik** [comment]
Unfortunately we can't access that URL. It sounds like the issue is with the implementation of the player on that site: if they use two different primitives for audio and displaying the annimation, they both need to listen to speed settings and adjust their logic. This is not something we can do, however, on their behalf in this extension.
