### ISSUE TITLE
Always play at x speed

### ISSUE THREAD

**Issue by mizagog** [igrigorik/videospeed#717]
Would love the option to lock playback speed.

I am using the extension on mobile, and the "remember speed option" dose not always work, and the UI is not responding on all players (gamespot.com)

I used to go to "Desktop version" on youtube and this was "remembering" the speed, and once in a while it will get reset.

**Comment by pepijnmm** [comment]
In the next release "Force last saved speed" will be available what will help with website that try to change the speed.(if on mobile you can sideload extensions you can download the master). why once in a while youtube will not use the rememberd speed I am not sure about. never kept my eye on it since sometimes I reset the speed when listening to music.

That the controller is not working is the same problem as  #690(gamespot has a extra layer on the video) . when this will be added by someone and if the solution would work on mobile I am not sure.

**Comment by mizagog** [comment]
Gamespot behaves fine on Desktop (firefox and Vivaldi), it is only on Firefox (Android) that I am seeing this. Butt the Force last saved speed sounds exactly like what I'm looking for on mobile. Thanks!

**Comment by mizagog** [comment]
i see the option to "Force last saved speed" and it is working great! thanks!
