### ISSUE TITLE
can't detect html5 player in iframe

### ISSUE THREAD

**Issue by huntertran** [igrigorik/videospeed#726]
some websites embedded iframe with the actual player inside the main page to prevent download. How can we overcome this?

**Comment by pepijnmm** [comment]
Videospeed doesn't support video downloading so I am not sure what the issue is. There are other extensions for that, this is just for changing the audio/video speed.

**Comment by huntertran** [comment]
for example: [https://animetvn.tv/](https://animetvn.tv/)

**Comment by pepijnmm** [comment]
I am not sure if animetvn is legal so I will just say how generally these websites work without going in detail on your link.
They use different video hosting platforms and use iframes to let it seem like you are watching the video on their website. Sometimes the iframe just exists of a video element with a video controller or sometimes the website has more things like the header of the video hoster and like button etc. 
They can use 10+ different hosting platforms to host the videos.
I never have had a problem with iframes before where videospeed didn't work. Sometimes the control could not be used because of a div that would be in front of it but the keyboard shortcuts always worked for me.
I would think that if you get the iframe URL and open it in your browser the video will still not have the speed controller because iframes are not really a problem for videospeed. maybe you can then figure out with debugging what is going wrong.

If you have a different URL that also doesn't work that doesn't have legal problems I will take a look at it.

**Comment by huntertran** [comment]
thanks anyway for this great extension
