### ISSUE TITLE
Can not see log data in console

### ISSUE THREAD

**Issue by iamgmujtaba** [igrigorik/videospeed#727]
Hi there,

I could not find the log data in the chrome browser. Even though, I have checked "Verbose" in the console setting. Any help?

https://github.com/igrigorik/videospeed/blob/56eb7a08459d6746a0019b0b0c4edf974c022114/inject.js#L39

Many thanks

**Comment by pepijnmm** [comment]
I am not sure where to change defaultLogLevel. Where did you check Verbose?(I can only see that it is set to 4 in default on line 22.
I would excpect to see a select in the options page I am not sure if it is missing or that I should look somewhere else.
I quick fix would ofcourse be to change the default loglevel on line 22 of inject.js. But that is probably not the way it should be handled.


@igrigorik ?

**Comment by iamgmujtaba** [comment]
Please find the attached file. 

![Devtool](https://user-images.githubusercontent.com/33286377/97847605-3bdfea80-1d33-11eb-8e10-d116a7bb2b14.png)

**Comment by pepijnmm** [comment]
It doesn't seem like this extension is using the log levels in chrome. We are now only using console.log(and on one place console.trace) to use chrome levels you will need to use the following:  console.error()/console.warn()/console.info()/console.debug()(debug is only visable with verbose enabled)

![image](https://user-images.githubusercontent.com/3217184/97854449-c0157c00-1cf9-11eb-8e3e-019b52785a2c.png)
you can change the loglevel here. Not sure why there is a defaultloglevel and a loglevel because it's never saved. just change the loglevel the the one you want(for example 6).
Atleast if you are loading the extension as a developer and not though the store.

**Comment by iamgmujtaba** [comment]
Thank you so much for your suggestion. I have changed the logLevel: 3 to 6 and it is working properly. Just for information, I have imported the extension as a developer mode.
I am closing this issue now :)
