### ISSUE TITLE
Control in the same spot as Netflix control in full screen

### ISSUE THREAD

**Issue by meeple142** [igrigorik/videospeed#75]
Rather than have you try to accommodate for every html 5 video player, hat if you added x and y % location settings so the user can just put it where they want it. So if I wanted it in the top right instead I would set location to something like x = 85%, y = 10%. 

By the way thank you for the awesome add on!

**Comment by igrigorik** [comment]
Ideally, it would be draggable.. My last attempt at that wasn't very productive though. As in, the basics worked, but it wasn't reliable and added a lot of complexity. But, perhaps that's more a comment about my implementation, not the fact that it can't or shouldn't be done :)

**Comment by atlas6523** [comment]
I would think 5 preset orientations would fix this problem for the majority (if not all) of video players.  Upper-left (current position), upper-middle, upper-right, middle-left and middle-right.  I exclude the bottom because that's where the original video player controls are almost always located.  I totally understand the desire to make it drag-able (being an idealistic problem-solver myself), but I think this would be a great in-the-middle solution, at least until you have time to invest into getting it "just right".  Anyways, thanks so much for this great tool.  Hope to hear from you soon.

**Comment by pjrobertson** [comment]
I came over here with the same problem. I agree an option in the preferences would be the simplest and best fix (for now at least). Even just two options of: "Top Left" and "Top Right" would do

**Comment by igrigorik** [comment]
Merging with https://github.com/igrigorik/videospeed/issues/82.
